es::ull::esit::app::middleware::model::Appetizer
Long es.ull.esit.app.middleware.model.Appetizer.appetizersId
Referenced by es.ull.esit.app.middleware.model.Appetizer.Appetizer, es.ull.esit.app.middleware.model.Appetizer.getAppetizersId, es.ull.esit.app.middleware.model.Appetizer.setAppetizersId.
String es.ull.esit.app.middleware.model.Appetizer.itemAppetizers
Referenced by es.ull.esit.app.middleware.model.Appetizer.Appetizer, es.ull.esit.app.middleware.model.Appetizer.getItemAppetizers, es.ull.esit.app.middleware.model.Appetizer.setItemAppetizers.
Integer es.ull.esit.app.middleware.model.Appetizer.appetizersPrice
Referenced by es.ull.esit.app.middleware.model.Appetizer.Appetizer, es.ull.esit.app.middleware.model.Appetizer.getAppetizersPrice, es.ull.esit.app.middleware.model.Appetizer.setAppetizersPrice.
Long es.ull.esit.app.middleware.model.Appetizer.receiptId
Referenced by es.ull.esit.app.middleware.model.Appetizer.Appetizer, es.ull.esit.app.middleware.model.Appetizer.getReceiptId, es.ull.esit.app.middleware.model.Appetizer.setReceiptId.
es.ull.esit.app.middleware.model.Appetizer.Appetizer()
References es.ull.esit.app.middleware.model.Appetizer.Appetizer.
Referenced by es.ull.esit.app.middleware.model.Appetizer.Appetizer.
es.ull.esit.app.middleware.model.Appetizer.Appetizer(Long appetizersId, String itemAppetizers, Integer appetizersPrice, Long receiptId)
Constructor with parameters.
appetizersId the appetizers ID itemAppetizers the appetizer item name appetizersPrice the appetizer price receiptId the receipt ID
References es.ull.esit.app.middleware.model.Appetizer.appetizersId, es.ull.esit.app.middleware.model.Appetizer.appetizersPrice, es.ull.esit.app.middleware.model.Appetizer.itemAppetizers, es.ull.esit.app.middleware.model.Appetizer.receiptId.
Long es.ull.esit.app.middleware.model.Appetizer.getAppetizersId()
Getters and Setters.
values of the attributes
References es.ull.esit.app.middleware.model.Appetizer.appetizersId.
void es.ull.esit.app.middleware.model.Appetizer.setAppetizersId(Long appetizersId)
Set appetizers ID.
appetizersId the appetizers ID
References es.ull.esit.app.middleware.model.Appetizer.appetizersId.
String es.ull.esit.app.middleware.model.Appetizer.getItemAppetizers()
Get item appetizers.
the appetizer item name
References es.ull.esit.app.middleware.model.Appetizer.itemAppetizers.
Referenced by es.ull.esit.app.adminProducts.jTable2MouseClicked.
void es.ull.esit.app.middleware.model.Appetizer.setItemAppetizers(String itemAppetizers)
Set item appetizers.
itemAppetizers the appetizer item name
References es.ull.esit.app.middleware.model.Appetizer.itemAppetizers.
Integer es.ull.esit.app.middleware.model.Appetizer.getAppetizersPrice()
Get appetizers price.
the appetizer price
References es.ull.esit.app.middleware.model.Appetizer.appetizersPrice.
Referenced by es.ull.esit.app.adminProducts.jTable2MouseClicked.
void es.ull.esit.app.middleware.model.Appetizer.setAppetizersPrice(Integer appetizersPrice)
Set appetizers price.
appetizersPrice the appetizer price
References es.ull.esit.app.middleware.model.Appetizer.appetizersPrice.
Long es.ull.esit.app.middleware.model.Appetizer.getReceiptId()
Get receipt ID.
the receipt ID
References es.ull.esit.app.middleware.model.Appetizer.receiptId.
void es.ull.esit.app.middleware.model.Appetizer.setReceiptId(Long receiptId)
Set receipt ID.
receiptId the receipt ID
References es.ull.esit.app.middleware.model.Appetizer.receiptId.