es::ull::esit::app::adminProducts
ApiClient es.ull.esit.app.adminProducts.apiClient
Cliente HTTP para llamadas al backend.
Referenced by es.ull.esit.app.adminProducts.adminProducts, es.ull.esit.app.adminProducts.jButton1ActionPerformed, es.ull.esit.app.adminProducts.jButton2ActionPerformed, es.ull.esit.app.adminProducts.jButton4ActionPerformed, es.ull.esit.app.adminProducts.jButton5ActionPerformed, es.ull.esit.app.adminProducts.jButton6ActionPerformed, es.ull.esit.app.adminProducts.jButton7ActionPerformed, es.ull.esit.app.adminProducts.jTable1MouseClicked, es.ull.esit.app.adminProducts.jTable2MouseClicked, es.ull.esit.app.adminProducts.jTable3MouseClicked.
javax.swing.JTextField es.ull.esit.app.adminProducts.itemname
Referenced by es.ull.esit.app.adminProducts.initComponents, es.ull.esit.app.adminProducts.jButton1ActionPerformed, es.ull.esit.app.adminProducts.jButton2ActionPerformed, es.ull.esit.app.adminProducts.jTable1MouseClicked.
javax.swing.JTextField es.ull.esit.app.adminProducts.itemname1
Referenced by es.ull.esit.app.adminProducts.initComponents, es.ull.esit.app.adminProducts.jButton4ActionPerformed, es.ull.esit.app.adminProducts.jButton5ActionPerformed, es.ull.esit.app.adminProducts.jTable2MouseClicked.
javax.swing.JTextField es.ull.esit.app.adminProducts.itemname2
Referenced by es.ull.esit.app.adminProducts.initComponents, es.ull.esit.app.adminProducts.jButton6ActionPerformed, es.ull.esit.app.adminProducts.jButton7ActionPerformed, es.ull.esit.app.adminProducts.jTable3MouseClicked.
javax.swing.JTextField es.ull.esit.app.adminProducts.itemprice
Referenced by es.ull.esit.app.adminProducts.initComponents, es.ull.esit.app.adminProducts.jButton1ActionPerformed, es.ull.esit.app.adminProducts.jButton2ActionPerformed, es.ull.esit.app.adminProducts.jTable1MouseClicked.
javax.swing.JTextField es.ull.esit.app.adminProducts.itemprice1
Referenced by es.ull.esit.app.adminProducts.initComponents, es.ull.esit.app.adminProducts.jButton4ActionPerformed, es.ull.esit.app.adminProducts.jButton5ActionPerformed, es.ull.esit.app.adminProducts.jTable2MouseClicked.
javax.swing.JTextField es.ull.esit.app.adminProducts.itemprice2
Referenced by es.ull.esit.app.adminProducts.initComponents, es.ull.esit.app.adminProducts.jButton6ActionPerformed, es.ull.esit.app.adminProducts.jButton7ActionPerformed, es.ull.esit.app.adminProducts.jTable3MouseClicked.
javax.swing.JButton es.ull.esit.app.adminProducts.jButton1
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JButton es.ull.esit.app.adminProducts.jButton2
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JButton es.ull.esit.app.adminProducts.jButton3
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JButton es.ull.esit.app.adminProducts.jButton4
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JButton es.ull.esit.app.adminProducts.jButton5
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JButton es.ull.esit.app.adminProducts.jButton6
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JButton es.ull.esit.app.adminProducts.jButton7
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JLabel es.ull.esit.app.adminProducts.jLabel1
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JLabel es.ull.esit.app.adminProducts.jLabel10
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JLabel es.ull.esit.app.adminProducts.jLabel2
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JLabel es.ull.esit.app.adminProducts.jLabel3
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JLabel es.ull.esit.app.adminProducts.jLabel4
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JLabel es.ull.esit.app.adminProducts.jLabel5
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JLabel es.ull.esit.app.adminProducts.jLabel6
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JLabel es.ull.esit.app.adminProducts.jLabel7
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JLabel es.ull.esit.app.adminProducts.jLabel8
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JLabel es.ull.esit.app.adminProducts.jLabel9
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JPanel es.ull.esit.app.adminProducts.jPanel1
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JPanel es.ull.esit.app.adminProducts.jPanel2
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JPanel es.ull.esit.app.adminProducts.jPanel3
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JPanel es.ull.esit.app.adminProducts.jPanel4
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JScrollPane es.ull.esit.app.adminProducts.jScrollPane1
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JScrollPane es.ull.esit.app.adminProducts.jScrollPane2
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JScrollPane es.ull.esit.app.adminProducts.jScrollPane3
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JTabbedPane es.ull.esit.app.adminProducts.jTabbedPane1
Referenced by es.ull.esit.app.adminProducts.initComponents.
javax.swing.JTable es.ull.esit.app.adminProducts.jTable1
Referenced by es.ull.esit.app.adminProducts.initComponents, es.ull.esit.app.adminProducts.jButton1ActionPerformed, es.ull.esit.app.adminProducts.jButton2ActionPerformed, es.ull.esit.app.adminProducts.jTable1MouseClicked.
javax.swing.JTable es.ull.esit.app.adminProducts.jTable2
Referenced by es.ull.esit.app.adminProducts.initComponents, es.ull.esit.app.adminProducts.jButton4ActionPerformed, es.ull.esit.app.adminProducts.jButton5ActionPerformed, es.ull.esit.app.adminProducts.jTable2MouseClicked.
javax.swing.JTable es.ull.esit.app.adminProducts.jTable3
Referenced by es.ull.esit.app.adminProducts.initComponents, es.ull.esit.app.adminProducts.jButton6ActionPerformed, es.ull.esit.app.adminProducts.jButton7ActionPerformed, es.ull.esit.app.adminProducts.jTable3MouseClicked.
DefaultTableModel es.ull.esit.app.adminProducts.modelDrink
Modelos de tabla para mostrar listas de productos.
DefaultTableModel es.ull.esit.app.adminProducts.modelappetizers
DefaultTableModel es.ull.esit.app.adminProducts.modelmaincourse
String [] es.ull.esit.app.adminProducts.columnNames
Cabeceras comunes de las tablas.
Long es.ull.esit.app.adminProducts.selectedDrinkID
IDs seleccionados actualmente en cada tabla (si hay seleccin).
Long es.ull.esit.app.adminProducts.selectedAppetizerID
Long es.ull.esit.app.adminProducts.selectedMainCourseID
es.ull.esit.app.adminProducts.adminProducts()
Creates new form adminProducts.
References es.ull.esit.app.adminProducts.apiClient, es.ull.esit.app.adminProducts.initComponents.
Referenced by es.ull.esit.app.adminProducts.main.
void es.ull.esit.app.adminProducts.loadDrinks()
Carga la lista de bebidas desde el backend y la vuelca en la tabla.
Captura excepciones y muestra un dilogo en caso de error de red.
void es.ull.esit.app.adminProducts.loadAppetizer()
Carga la lista de aperitivos desde el backend y la vuelca en la tabla.
void es.ull.esit.app.adminProducts.loadmainCourse()
Carga la lista de platos principales desde el backend y la vuela en la tabla.
void es.ull.esit.app.adminProducts.jButton2ActionPerformed(java.awt.event.ActionEvent evt)
Manejador del botn "Add" (Drinks).
Crea un objeto Drink con los datos del formulario y lo enva al backend mediante ApiClient. Tras crear el recurso refresca la tabla. evt evento de accin
References es.ull.esit.app.adminProducts.apiClient, es.ull.esit.app.adminProducts.itemname, es.ull.esit.app.adminProducts.itemprice, es.ull.esit.app.adminProducts.jTable1.
void es.ull.esit.app.adminProducts.initComponents()
This method is called from within the constructor to initialize the form.
WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
References es.ull.esit.app.adminProducts.initComponents, es.ull.esit.app.adminProducts.itemname, es.ull.esit.app.adminProducts.itemname1, es.ull.esit.app.adminProducts.itemname2, es.ull.esit.app.adminProducts.itemprice, es.ull.esit.app.adminProducts.itemprice1, es.ull.esit.app.adminProducts.itemprice2, es.ull.esit.app.adminProducts.jButton1, es.ull.esit.app.adminProducts.jButton2, es.ull.esit.app.adminProducts.jButton3, es.ull.esit.app.adminProducts.jButton4, es.ull.esit.app.adminProducts.jButton5, es.ull.esit.app.adminProducts.jButton6, es.ull.esit.app.adminProducts.jButton7, es.ull.esit.app.adminProducts.jLabel1, es.ull.esit.app.adminProducts.jLabel10, es.ull.esit.app.adminProducts.jLabel2, es.ull.esit.app.adminProducts.jLabel3, es.ull.esit.app.adminProducts.jLabel4, es.ull.esit.app.adminProducts.jLabel5, es.ull.esit.app.adminProducts.jLabel6, es.ull.esit.app.adminProducts.jLabel7, es.ull.esit.app.adminProducts.jLabel8, es.ull.esit.app.adminProducts.jLabel9, es.ull.esit.app.adminProducts.jPanel1, es.ull.esit.app.adminProducts.jPanel2, es.ull.esit.app.adminProducts.jPanel3, es.ull.esit.app.adminProducts.jPanel4, es.ull.esit.app.adminProducts.jScrollPane1, es.ull.esit.app.adminProducts.jScrollPane2, es.ull.esit.app.adminProducts.jScrollPane3, es.ull.esit.app.adminProducts.jTabbedPane1, es.ull.esit.app.adminProducts.jTable1, es.ull.esit.app.adminProducts.jTable2, es.ull.esit.app.adminProducts.jTable3.
Referenced by es.ull.esit.app.adminProducts.adminProducts, es.ull.esit.app.adminProducts.initComponents.
void es.ull.esit.app.adminProducts.jButton3ActionPerformed(java.awt.event.ActionEvent evt)
Manejador del botn "Add" (Drinks).
Crea un objeto Drink con los datos del formulario y lo enva al backend mediante ApiClient. Tras crear el recurso refresca la tabla. evt evento de accin
void es.ull.esit.app.adminProducts.jButton5ActionPerformed(java.awt.event.ActionEvent evt)
Manejador del botn "Add" (Appetizers).
Crea un objeto Appetizer con los datos del formulario y lo enva al backend mediante ApiClient. Tras crear el recurso refresca la tabla. evt evento de accin
References es.ull.esit.app.adminProducts.apiClient, es.ull.esit.app.adminProducts.itemname1, es.ull.esit.app.adminProducts.itemprice1, es.ull.esit.app.adminProducts.jTable2.
void es.ull.esit.app.adminProducts.jButton7ActionPerformed(java.awt.event.ActionEvent evt)
Manejador del botn "Add" (MainCourse).
Crea un objeto MainCourse con los datos del formulario y lo enva al backend mediante ApiClient. Tras crear el recurso refresca la tabla. evt evento de accin
References es.ull.esit.app.adminProducts.apiClient, es.ull.esit.app.adminProducts.itemname2, es.ull.esit.app.adminProducts.itemprice2, es.ull.esit.app.adminProducts.jTable3.
void es.ull.esit.app.adminProducts.jTable1KeyPressed(java.awt.event.KeyEvent evt)
Manejador de teclas presionadas en la tabla de bebidas.
Permite capturar el ID de la bebida seleccionada al navegar con el teclado. evt Evento de tecla generado por la accin del usuario. void
void es.ull.esit.app.adminProducts.jTable1MouseClicked(java.awt.event.MouseEvent evt)
Manejador de clics en la tabla de bebidas.
Al hacer clic en una fila, se captura el ID de la bebida seleccionada para futuras operaciones de actualizacin. evt Evento de ratn generado por el clic. void
References es.ull.esit.app.adminProducts.apiClient, es.ull.esit.app.middleware.model.Drink.getDrinksPrice, es.ull.esit.app.middleware.model.Drink.getItemDrinks, es.ull.esit.app.adminProducts.itemname, es.ull.esit.app.adminProducts.itemprice, es.ull.esit.app.adminProducts.jTable1.
void es.ull.esit.app.adminProducts.jTable2MouseClicked(java.awt.event.MouseEvent evt)
Manejador de clics en la tabla de aperitivos.
Al hacer clic en una fila, se captura el ID del aperitivo seleccionado para futuras operaciones de actualizacin. evt Evento de ratn generado por el clic. void
References es.ull.esit.app.adminProducts.apiClient, es.ull.esit.app.middleware.model.Appetizer.getAppetizersPrice, es.ull.esit.app.middleware.model.Appetizer.getItemAppetizers, es.ull.esit.app.adminProducts.itemname1, es.ull.esit.app.adminProducts.itemprice1, es.ull.esit.app.adminProducts.jTable2.
void es.ull.esit.app.adminProducts.jTable3MouseClicked(java.awt.event.MouseEvent evt)
Manejador de clics en la tabla de platos principales.
Al hacer clic en una fila, se captura el ID del plato seleccionado para futuras operaciones de actualizacin. evt Evento de ratn generado por el clic. void
References es.ull.esit.app.adminProducts.apiClient, es.ull.esit.app.middleware.model.MainCourse.getFoodPrice, es.ull.esit.app.middleware.model.MainCourse.getItemFood, es.ull.esit.app.adminProducts.itemname2, es.ull.esit.app.adminProducts.itemprice2, es.ull.esit.app.adminProducts.jTable3.
void es.ull.esit.app.adminProducts.jButton1ActionPerformed(java.awt.event.ActionEvent evt)
Manejador del botn "Update" (Drinks).
Actualiza el precio de la bebida seleccionada en el backend utilizando ApiClient. Refresca la tabla tras la actualizacin. evt evento de accin
References es.ull.esit.app.adminProducts.apiClient, es.ull.esit.app.adminProducts.itemname, es.ull.esit.app.adminProducts.itemprice, es.ull.esit.app.adminProducts.jTable1.
void es.ull.esit.app.adminProducts.jButton4ActionPerformed(java.awt.event.ActionEvent evt)
Manejador del botn "Update" (Appetizers).
Actualiza el precio del aperitivo seleccionado en el backend utilizando ApiClient. Refresca la tabla tras la actualizacin. evt evento de accin
References es.ull.esit.app.adminProducts.apiClient, es.ull.esit.app.adminProducts.itemname1, es.ull.esit.app.adminProducts.itemprice1, es.ull.esit.app.adminProducts.jTable2.
void es.ull.esit.app.adminProducts.jButton6ActionPerformed(java.awt.event.ActionEvent evt)
Manejador del botn "Update" (MainCourse).
Actualiza el precio del plato seleccionado en el backend utilizando ApiClient. Refresca la tabla tras la actualizacin. evt evento de accin
References es.ull.esit.app.adminProducts.apiClient, es.ull.esit.app.adminProducts.itemname2, es.ull.esit.app.adminProducts.itemprice2, es.ull.esit.app.adminProducts.jTable3.
static void es.ull.esit.app.adminProducts.main(String args[])
args the command line arguments
References es.ull.esit.app.adminProducts.adminProducts.