es::ull::esit::app::Frame1
int es.ull.esit.app.Frame1.colaNum
Contadores de unidades seleccionadas por producto.
int es.ull.esit.app.Frame1.upNum
int es.ull.esit.app.Frame1.orangeNum
int es.ull.esit.app.Frame1.mojitoNum
int es.ull.esit.app.Frame1.friesNum
int es.ull.esit.app.Frame1.moltenNum
int es.ull.esit.app.Frame1.macNum
int es.ull.esit.app.Frame1.shrimpNum
int es.ull.esit.app.Frame1.pizzaNum
int es.ull.esit.app.Frame1.pastaNum
int es.ull.esit.app.Frame1.salmonNum
int es.ull.esit.app.Frame1.spaghettiNum
double es.ull.esit.app.Frame1.cola_Price
Precios calculados por producto (cantidad * coste unitario).
double es.ull.esit.app.Frame1.up_Price
double es.ull.esit.app.Frame1.mojito_Price
double es.ull.esit.app.Frame1.orange_Price
double es.ull.esit.app.Frame1.molten_Price
double es.ull.esit.app.Frame1.mac_Price
double es.ull.esit.app.Frame1.fries_Price
double es.ull.esit.app.Frame1.shrimp_Price
double es.ull.esit.app.Frame1.pizza_Price
double es.ull.esit.app.Frame1.pasta_Price
double es.ull.esit.app.Frame1.salmon_Price
double es.ull.esit.app.Frame1.spaghetti_Price
final double es.ull.esit.app.Frame1.colaCost
Costes unitarios constantes por producto.
final double es.ull.esit.app.Frame1.upCost
final double es.ull.esit.app.Frame1.mojitoCost
final double es.ull.esit.app.Frame1.orangeCost
final double es.ull.esit.app.Frame1.moltenCost
final double es.ull.esit.app.Frame1.macCost
final double es.ull.esit.app.Frame1.friesCost
final double es.ull.esit.app.Frame1.shrimpCost
final double es.ull.esit.app.Frame1.pizzaCost
final double es.ull.esit.app.Frame1.pastaCost
final double es.ull.esit.app.Frame1.salmonCost
final double es.ull.esit.app.Frame1.spaghettiCost
double es.ull.esit.app.Frame1.subTotal
Totales y valores derivados.
double es.ull.esit.app.Frame1.vat
double es.ull.esit.app.Frame1.total
int es.ull.esit.app.Frame1.receiptNo
Número de recibo actual (se usa al guardar).
PrintWriter es.ull.esit.app.Frame1.output
Escritor para guardar recibos en disco.
javax.swing.JPanel es.ull.esit.app.Frame1.AppetizerPnl
Panel de aperitivos.
Referenced by es.ull.esit.app.Frame1.initComponents.
javax.swing.JPanel es.ull.esit.app.Frame1.DrinksPnl
Panel de bebidas.
Referenced by es.ull.esit.app.Frame1.initComponents.
javax.swing.JPanel es.ull.esit.app.Frame1.MainCoursePnl
Panel de platos principales.
Referenced by es.ull.esit.app.Frame1.initComponents.
javax.swing.JSpinner es.ull.esit.app.Frame1.colaCountS
Spinner para la cantidad de Cola.
Referenced by es.ull.esit.app.Frame1.colaCountSStateChanged, es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.newReceiptBtnActionPerformed.
javax.swing.JLabel es.ull.esit.app.Frame1.colaLbl
Etiqueta de Cola.
Referenced by es.ull.esit.app.Frame1.initComponents.
javax.swing.JLabel es.ull.esit.app.Frame1.colaPriceLbl
Precio calculado de Cola.
Referenced by es.ull.esit.app.Frame1.colaCountSStateChanged, es.ull.esit.app.Frame1.initComponents.
javax.swing.JSpinner es.ull.esit.app.Frame1.friesCountS
Spinner para las Truffel Fries.
Referenced by es.ull.esit.app.Frame1.friesCountSStateChanged, es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.newReceiptBtnActionPerformed.
javax.swing.JLabel es.ull.esit.app.Frame1.friesLbl
Etiqueta de Fries.
Referenced by es.ull.esit.app.Frame1.initComponents.
javax.swing.JLabel es.ull.esit.app.Frame1.friesPriceLbl
Precio calculado de Fries.
Referenced by es.ull.esit.app.Frame1.friesCountSStateChanged, es.ull.esit.app.Frame1.initComponents.
javax.swing.JButton es.ull.esit.app.Frame1.goBackMenueBtn
Botón para volver al menú de login.
Referenced by es.ull.esit.app.Frame1.initComponents.
javax.swing.JLabel es.ull.esit.app.Frame1.jLabel1
Referenced by es.ull.esit.app.Frame1.initComponents.
javax.swing.JLabel es.ull.esit.app.Frame1.jLabel2
Referenced by es.ull.esit.app.Frame1.initComponents.
javax.swing.JPanel es.ull.esit.app.Frame1.jPanel1
Referenced by es.ull.esit.app.Frame1.initComponents.
javax.swing.JPanel es.ull.esit.app.Frame1.jPanel2
Referenced by es.ull.esit.app.Frame1.initComponents.
javax.swing.JSpinner es.ull.esit.app.Frame1.macCountS
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.macCountSStateChanged, es.ull.esit.app.Frame1.newReceiptBtnActionPerformed.
javax.swing.JLabel es.ull.esit.app.Frame1.macLbl
Referenced by es.ull.esit.app.Frame1.initComponents.
javax.swing.JLabel es.ull.esit.app.Frame1.macPriceLbl
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.macCountSStateChanged.
javax.swing.JSpinner es.ull.esit.app.Frame1.mojitoCountS
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.mojitoCountSStateChanged, es.ull.esit.app.Frame1.newReceiptBtnActionPerformed.
javax.swing.JLabel es.ull.esit.app.Frame1.mojitoLbl
Referenced by es.ull.esit.app.Frame1.initComponents.
javax.swing.JLabel es.ull.esit.app.Frame1.mojitoPriceLbl
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.mojitoCountSStateChanged.
javax.swing.JSpinner es.ull.esit.app.Frame1.moltenCountS
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.moltenCountSStateChanged, es.ull.esit.app.Frame1.newReceiptBtnActionPerformed.
javax.swing.JLabel es.ull.esit.app.Frame1.moltenLbl
Referenced by es.ull.esit.app.Frame1.initComponents.
javax.swing.JLabel es.ull.esit.app.Frame1.moltenPriceLbl
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.moltenCountSStateChanged.
javax.swing.JButton es.ull.esit.app.Frame1.newReceiptBtn
Botón para crear nuevo recibo.
Referenced by es.ull.esit.app.Frame1.initComponents.
javax.swing.JLabel es.ull.esit.app.Frame1.orangLbl
Referenced by es.ull.esit.app.Frame1.initComponents.
javax.swing.JSpinner es.ull.esit.app.Frame1.orangeCountS
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.newReceiptBtnActionPerformed, es.ull.esit.app.Frame1.orangeCountSStateChanged.
javax.swing.JLabel es.ull.esit.app.Frame1.orangePriceLbl
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.orangeCountSStateChanged.
javax.swing.JCheckBox es.ull.esit.app.Frame1.pastaChicken
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.newReceiptBtnActionPerformed, es.ull.esit.app.Frame1.pastaChickenActionPerformed.
javax.swing.JSpinner es.ull.esit.app.Frame1.pastaCountS
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.newReceiptBtnActionPerformed, es.ull.esit.app.Frame1.pastaCountSStateChanged.
javax.swing.JLabel es.ull.esit.app.Frame1.pastaLbl
Referenced by es.ull.esit.app.Frame1.initComponents.
javax.swing.JLabel es.ull.esit.app.Frame1.pastaPriceLbl
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.pastaChickenActionPerformed, es.ull.esit.app.Frame1.pastaCountSStateChanged.
javax.swing.JButton es.ull.esit.app.Frame1.payBtn
Botón de pago.
Referenced by es.ull.esit.app.Frame1.initComponents.
javax.swing.JSpinner es.ull.esit.app.Frame1.pizzaCountS
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.newReceiptBtnActionPerformed, es.ull.esit.app.Frame1.pizzaCountSStateChanged.
javax.swing.JLabel es.ull.esit.app.Frame1.pizzaLbl
Referenced by es.ull.esit.app.Frame1.initComponents.
javax.swing.JLabel es.ull.esit.app.Frame1.pizzaPriceLbl
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.pizzaCountSStateChanged, es.ull.esit.app.Frame1.pizzaSpicyActionPerformed.
javax.swing.JCheckBox es.ull.esit.app.Frame1.pizzaSpicy
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.newReceiptBtnActionPerformed, es.ull.esit.app.Frame1.pizzaSpicyActionPerformed.
javax.swing.JLabel es.ull.esit.app.Frame1.receiptNoLbl
Etiqueta con número de recibo.
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.newReceiptBtnActionPerformed.
javax.swing.JSpinner es.ull.esit.app.Frame1.salmonCountS
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.newReceiptBtnActionPerformed, es.ull.esit.app.Frame1.salmonCountSStateChanged.
javax.swing.JLabel es.ull.esit.app.Frame1.salmonLbl
Referenced by es.ull.esit.app.Frame1.initComponents.
javax.swing.JLabel es.ull.esit.app.Frame1.salmonPriceLbl
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.salmonCountSStateChanged, es.ull.esit.app.Frame1.salmonRiceActionPerformed.
javax.swing.JCheckBox es.ull.esit.app.Frame1.salmonRice
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.newReceiptBtnActionPerformed, es.ull.esit.app.Frame1.salmonRiceActionPerformed.
javax.swing.JButton es.ull.esit.app.Frame1.saveReceiptBtn
Botón para guardar recibo en disco.
Referenced by es.ull.esit.app.Frame1.initComponents.
javax.swing.JSpinner es.ull.esit.app.Frame1.shrimpCountS
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.newReceiptBtnActionPerformed, es.ull.esit.app.Frame1.shrimpCountSStateChanged.
javax.swing.JLabel es.ull.esit.app.Frame1.shrimpLbl
Referenced by es.ull.esit.app.Frame1.initComponents.
javax.swing.JLabel es.ull.esit.app.Frame1.shrimpPriceLbl
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.shrimpCountSStateChanged.
javax.swing.JSpinner es.ull.esit.app.Frame1.spaghettiCountS
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.newReceiptBtnActionPerformed, es.ull.esit.app.Frame1.spaghettiCountSStateChanged.
javax.swing.JLabel es.ull.esit.app.Frame1.spaghettiLbl
Referenced by es.ull.esit.app.Frame1.initComponents.
javax.swing.JLabel es.ull.esit.app.Frame1.spaghettiPriceLbl
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.spaghettiCountSStateChanged, es.ull.esit.app.Frame1.spaghettiSpicyActionPerformed.
javax.swing.JCheckBox es.ull.esit.app.Frame1.spaghettiSpicy
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.newReceiptBtnActionPerformed, es.ull.esit.app.Frame1.spaghettiSpicyActionPerformed.
javax.swing.JLabel es.ull.esit.app.Frame1.subTotalLbl
Etiqueta de subtotal.
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.newReceiptBtnActionPerformed, es.ull.esit.app.Frame1.payBtnActionPerformed.
javax.swing.JLabel es.ull.esit.app.Frame1.totalLbl
Etiqueta de total.
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.newReceiptBtnActionPerformed, es.ull.esit.app.Frame1.payBtnActionPerformed.
javax.swing.JSpinner es.ull.esit.app.Frame1.upCountS
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.newReceiptBtnActionPerformed, es.ull.esit.app.Frame1.upCountSStateChanged.
javax.swing.JLabel es.ull.esit.app.Frame1.upLbl
Referenced by es.ull.esit.app.Frame1.initComponents.
javax.swing.JLabel es.ull.esit.app.Frame1.upPriceLbl
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.upCountSStateChanged.
javax.swing.JLabel es.ull.esit.app.Frame1.vatLbl
Referenced by es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.newReceiptBtnActionPerformed, es.ull.esit.app.Frame1.payBtnActionPerformed.
es.ull.esit.app.Frame1.Frame1()
Creates new form Frame1.
References es.ull.esit.app.Frame1.initComponents.
Referenced by es.ull.esit.app.Frame1.main.
void es.ull.esit.app.Frame1.loadPrice()
Carga los precios de los productos desde una fuente externa.
Actualmente no implementado.
void es.ull.esit.app.Frame1.initComponents()
This method is called from within the constructor to initialize the form.
WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
References es.ull.esit.app.Frame1.AppetizerPnl, es.ull.esit.app.Frame1.colaCountS, es.ull.esit.app.Frame1.colaLbl, es.ull.esit.app.Frame1.colaPriceLbl, es.ull.esit.app.Frame1.DrinksPnl, es.ull.esit.app.Frame1.friesCountS, es.ull.esit.app.Frame1.friesLbl, es.ull.esit.app.Frame1.friesPriceLbl, es.ull.esit.app.Frame1.goBackMenueBtn, es.ull.esit.app.Frame1.initComponents, es.ull.esit.app.Frame1.jLabel1, es.ull.esit.app.Frame1.jLabel2, es.ull.esit.app.Frame1.jPanel1, es.ull.esit.app.Frame1.jPanel2, es.ull.esit.app.Frame1.macCountS, es.ull.esit.app.Frame1.macLbl, es.ull.esit.app.Frame1.macPriceLbl, es.ull.esit.app.Frame1.MainCoursePnl, es.ull.esit.app.Frame1.mojitoCountS, es.ull.esit.app.Frame1.mojitoLbl, es.ull.esit.app.Frame1.mojitoPriceLbl, es.ull.esit.app.Frame1.moltenCountS, es.ull.esit.app.Frame1.moltenLbl, es.ull.esit.app.Frame1.moltenPriceLbl, es.ull.esit.app.Frame1.newReceiptBtn, es.ull.esit.app.Frame1.orangeCountS, es.ull.esit.app.Frame1.orangePriceLbl, es.ull.esit.app.Frame1.orangLbl, es.ull.esit.app.Frame1.pastaChicken, es.ull.esit.app.Frame1.pastaCountS, es.ull.esit.app.Frame1.pastaLbl, es.ull.esit.app.Frame1.pastaPriceLbl, es.ull.esit.app.Frame1.payBtn, es.ull.esit.app.Frame1.pizzaCountS, es.ull.esit.app.Frame1.pizzaLbl, es.ull.esit.app.Frame1.pizzaPriceLbl, es.ull.esit.app.Frame1.pizzaSpicy, es.ull.esit.app.Frame1.receiptNoLbl, es.ull.esit.app.Frame1.salmonCountS, es.ull.esit.app.Frame1.salmonLbl, es.ull.esit.app.Frame1.salmonPriceLbl, es.ull.esit.app.Frame1.salmonRice, es.ull.esit.app.Frame1.saveReceiptBtn, es.ull.esit.app.Frame1.shrimpCountS, es.ull.esit.app.Frame1.shrimpLbl, es.ull.esit.app.Frame1.shrimpPriceLbl, es.ull.esit.app.Frame1.spaghettiCountS, es.ull.esit.app.Frame1.spaghettiLbl, es.ull.esit.app.Frame1.spaghettiPriceLbl, es.ull.esit.app.Frame1.spaghettiSpicy, es.ull.esit.app.Frame1.subTotalLbl, es.ull.esit.app.Frame1.totalLbl, es.ull.esit.app.Frame1.upCountS, es.ull.esit.app.Frame1.upLbl, es.ull.esit.app.Frame1.upPriceLbl, es.ull.esit.app.Frame1.vatLbl.
Referenced by es.ull.esit.app.Frame1.Frame1, es.ull.esit.app.Frame1.initComponents.
void es.ull.esit.app.Frame1.colaCountSStateChanged(javax.swing.event.ChangeEvent evt)
Called when the state of the colaCountS spinner changes.
evt the change event
References es.ull.esit.app.Frame1.colaCountS, es.ull.esit.app.Frame1.colaPriceLbl.
void es.ull.esit.app.Frame1.upCountSStateChanged(javax.swing.event.ChangeEvent evt)
Called when the state of the upCountS spinner changes.
evt the change event
References es.ull.esit.app.Frame1.upCountS, es.ull.esit.app.Frame1.upPriceLbl.
void es.ull.esit.app.Frame1.mojitoCountSStateChanged(javax.swing.event.ChangeEvent evt)
Called when the state of the mojitoCountS spinner changes.
evt the change event
References es.ull.esit.app.Frame1.mojitoCountS, es.ull.esit.app.Frame1.mojitoPriceLbl.
void es.ull.esit.app.Frame1.orangeCountSStateChanged(javax.swing.event.ChangeEvent evt)
Called when the state of the orangeCountS spinner changes.
evt the change event
References es.ull.esit.app.Frame1.orangeCountS, es.ull.esit.app.Frame1.orangePriceLbl.
void es.ull.esit.app.Frame1.friesCountSStateChanged(javax.swing.event.ChangeEvent evt)
Called when the state of the friesCountS spinner changes.
evt the change event
References es.ull.esit.app.Frame1.friesCountS, es.ull.esit.app.Frame1.friesPriceLbl.
void es.ull.esit.app.Frame1.moltenCountSStateChanged(javax.swing.event.ChangeEvent evt)
Called when the state of the moltenCountS spinner changes.
evt the change event
References es.ull.esit.app.Frame1.moltenCountS, es.ull.esit.app.Frame1.moltenPriceLbl.
void es.ull.esit.app.Frame1.shrimpCountSStateChanged(javax.swing.event.ChangeEvent evt)
Called when the state of the shrimpCountS spinner changes.
evt the change event
References es.ull.esit.app.Frame1.shrimpCountS, es.ull.esit.app.Frame1.shrimpPriceLbl.
void es.ull.esit.app.Frame1.macCountSStateChanged(javax.swing.event.ChangeEvent evt)
Called when the state of the macCountS spinner changes.
evt the change event
References es.ull.esit.app.Frame1.macCountS, es.ull.esit.app.Frame1.macPriceLbl.
void es.ull.esit.app.Frame1.pizzaCountSStateChanged(javax.swing.event.ChangeEvent evt)
Called when the state of the pizzaCountS spinner changes.
evt the change event
References es.ull.esit.app.Frame1.pizzaCountS, es.ull.esit.app.Frame1.pizzaPriceLbl.
void es.ull.esit.app.Frame1.pastaCountSStateChanged(javax.swing.event.ChangeEvent evt)
Called when the state of the pastaCountS spinner changes.
evt the change event
References es.ull.esit.app.Frame1.pastaCountS, es.ull.esit.app.Frame1.pastaPriceLbl.
void es.ull.esit.app.Frame1.spaghettiCountSStateChanged(javax.swing.event.ChangeEvent evt)
Called when the state of the spaghettiCountS spinner changes.
evt the change event
References es.ull.esit.app.Frame1.spaghettiCountS, es.ull.esit.app.Frame1.spaghettiPriceLbl.
void es.ull.esit.app.Frame1.salmonCountSStateChanged(javax.swing.event.ChangeEvent evt)
Called when the state of the salmonCountS spinner changes.
evt the change event
References es.ull.esit.app.Frame1.salmonCountS, es.ull.esit.app.Frame1.salmonPriceLbl.
void es.ull.esit.app.Frame1.spaghettiSpicyActionPerformed(java.awt.event.ActionEvent evt)
Called when the spaghettiSpicy checkbox is toggled.
evt the action event
References es.ull.esit.app.Frame1.spaghettiPriceLbl, es.ull.esit.app.Frame1.spaghettiSpicy.
void es.ull.esit.app.Frame1.pizzaSpicyActionPerformed(java.awt.event.ActionEvent evt)
Called when the pizzaSpicy checkbox is toggled.
evt the action event
References es.ull.esit.app.Frame1.pizzaPriceLbl, es.ull.esit.app.Frame1.pizzaSpicy.
void es.ull.esit.app.Frame1.pastaChickenActionPerformed(java.awt.event.ActionEvent evt)
Called when the pastaChicken checkbox is toggled.
evt the action event
References es.ull.esit.app.Frame1.pastaChicken, es.ull.esit.app.Frame1.pastaPriceLbl.
void es.ull.esit.app.Frame1.salmonRiceActionPerformed(java.awt.event.ActionEvent evt)
Called when the salmonRice checkbox is toggled.
evt the action event
References es.ull.esit.app.Frame1.salmonPriceLbl, es.ull.esit.app.Frame1.salmonRice.
void es.ull.esit.app.Frame1.payBtnActionPerformed(java.awt.event.ActionEvent evt)
Called when the payBtn button is clicked.
evt the action event
References es.ull.esit.app.Frame1.subTotalLbl, es.ull.esit.app.Frame1.totalLbl, es.ull.esit.app.Frame1.vatLbl.
void es.ull.esit.app.Frame1.saveReceiptBtnActionPerformed(java.awt.event.ActionEvent evt)
Called when the saveReceiptBtn button is clicked.
evt the action event
void es.ull.esit.app.Frame1.newReceiptBtnActionPerformed(java.awt.event.ActionEvent evt)
Called when the newReceiptBtn button is clicked.
evt the action event
References es.ull.esit.app.Frame1.colaCountS, es.ull.esit.app.Frame1.friesCountS, es.ull.esit.app.Frame1.macCountS, es.ull.esit.app.Frame1.mojitoCountS, es.ull.esit.app.Frame1.moltenCountS, es.ull.esit.app.Frame1.orangeCountS, es.ull.esit.app.Frame1.pastaChicken, es.ull.esit.app.Frame1.pastaCountS, es.ull.esit.app.Frame1.pizzaCountS, es.ull.esit.app.Frame1.pizzaSpicy, es.ull.esit.app.Frame1.receiptNoLbl, es.ull.esit.app.Frame1.salmonCountS, es.ull.esit.app.Frame1.salmonRice, es.ull.esit.app.Frame1.shrimpCountS, es.ull.esit.app.Frame1.spaghettiCountS, es.ull.esit.app.Frame1.spaghettiSpicy, es.ull.esit.app.Frame1.subTotalLbl, es.ull.esit.app.Frame1.totalLbl, es.ull.esit.app.Frame1.upCountS, es.ull.esit.app.Frame1.vatLbl.
void es.ull.esit.app.Frame1.goBackMenueBtnActionPerformed(java.awt.event.ActionEvent evt)
Called when the goBackMenueBtn button is clicked.
evt the action event
static void es.ull.esit.app.Frame1.main(String args[])
args the command line arguments
References es.ull.esit.app.Frame1.Frame1.