es::ull::esit::app::middleware::model::Drink
Long es.ull.esit.app.middleware.model.Drink.drinksId
Referenced by es.ull.esit.app.middleware.model.Drink.Drink, es.ull.esit.app.middleware.model.Drink.getDrinksId, es.ull.esit.app.middleware.model.Drink.setDrinksId.
String es.ull.esit.app.middleware.model.Drink.itemDrinks
Referenced by es.ull.esit.app.middleware.model.Drink.Drink, es.ull.esit.app.middleware.model.Drink.getItemDrinks, es.ull.esit.app.middleware.model.Drink.setItemDrinks.
Integer es.ull.esit.app.middleware.model.Drink.drinksPrice
Referenced by es.ull.esit.app.middleware.model.Drink.Drink, es.ull.esit.app.middleware.model.Drink.getDrinksPrice, es.ull.esit.app.middleware.model.Drink.setDrinksPrice.
Long es.ull.esit.app.middleware.model.Drink.receiptId
Referenced by es.ull.esit.app.middleware.model.Drink.Drink, es.ull.esit.app.middleware.model.Drink.getReceiptId, es.ull.esit.app.middleware.model.Drink.setReceiptId.
es.ull.esit.app.middleware.model.Drink.Drink()
References es.ull.esit.app.middleware.model.Drink.Drink.
Referenced by es.ull.esit.app.middleware.model.Drink.Drink.
es.ull.esit.app.middleware.model.Drink.Drink(Long drinksId, String itemDrinks, Integer drinksPrice, Long receiptId)
Constructor with parameters.
drinksId the drinks ID itemDrinks the drink item name drinksPrice the drink price receiptId the receipt ID
References es.ull.esit.app.middleware.model.Drink.drinksId, es.ull.esit.app.middleware.model.Drink.drinksPrice, es.ull.esit.app.middleware.model.Drink.itemDrinks, es.ull.esit.app.middleware.model.Drink.receiptId.
Long es.ull.esit.app.middleware.model.Drink.getDrinksId()
Getters and Setters.
values of the attributes
References es.ull.esit.app.middleware.model.Drink.drinksId.
void es.ull.esit.app.middleware.model.Drink.setDrinksId(Long drinksId)
Set drinks ID.
drinksId the drinks ID
References es.ull.esit.app.middleware.model.Drink.drinksId.
String es.ull.esit.app.middleware.model.Drink.getItemDrinks()
Get item drinks.
the drink item name
References es.ull.esit.app.middleware.model.Drink.itemDrinks.
Referenced by es.ull.esit.app.adminProducts.jTable1MouseClicked.
void es.ull.esit.app.middleware.model.Drink.setItemDrinks(String itemDrinks)
Set item drinks.
itemDrinks the drink item name
References es.ull.esit.app.middleware.model.Drink.itemDrinks.
Integer es.ull.esit.app.middleware.model.Drink.getDrinksPrice()
Get drinks price.
the drink price
References es.ull.esit.app.middleware.model.Drink.drinksPrice.
Referenced by es.ull.esit.app.adminProducts.jTable1MouseClicked.
void es.ull.esit.app.middleware.model.Drink.setDrinksPrice(Integer drinksPrice)
Set drinks price.
drinksPrice the drink price
References es.ull.esit.app.middleware.model.Drink.drinksPrice.
Long es.ull.esit.app.middleware.model.Drink.getReceiptId()
Get receipt ID.
the receipt ID
References es.ull.esit.app.middleware.model.Drink.receiptId.
void es.ull.esit.app.middleware.model.Drink.setReceiptId(Long receiptId)
Set receipt ID.
receiptId the receipt ID
References es.ull.esit.app.middleware.model.Drink.receiptId.