es::ull::esit::app::middleware::model::MainCourse
Long es.ull.esit.app.middleware.model.MainCourse.foodId
Referenced by es.ull.esit.app.middleware.model.MainCourse.getFoodId, es.ull.esit.app.middleware.model.MainCourse.MainCourse, es.ull.esit.app.middleware.model.MainCourse.setFoodId.
String es.ull.esit.app.middleware.model.MainCourse.itemFood
Referenced by es.ull.esit.app.middleware.model.MainCourse.getItemFood, es.ull.esit.app.middleware.model.MainCourse.MainCourse, es.ull.esit.app.middleware.model.MainCourse.setItemFood.
Integer es.ull.esit.app.middleware.model.MainCourse.foodPrice
Referenced by es.ull.esit.app.middleware.model.MainCourse.getFoodPrice, es.ull.esit.app.middleware.model.MainCourse.MainCourse, es.ull.esit.app.middleware.model.MainCourse.setFoodPrice.
Long es.ull.esit.app.middleware.model.MainCourse.receiptId
Referenced by es.ull.esit.app.middleware.model.MainCourse.getReceiptId, es.ull.esit.app.middleware.model.MainCourse.MainCourse, es.ull.esit.app.middleware.model.MainCourse.setReceiptId.
es.ull.esit.app.middleware.model.MainCourse.MainCourse()
References es.ull.esit.app.middleware.model.MainCourse.MainCourse.
Referenced by es.ull.esit.app.middleware.model.MainCourse.MainCourse.
es.ull.esit.app.middleware.model.MainCourse.MainCourse(Long foodId, String itemFood, Integer foodPrice, Long receiptId)
Constructor with parameters.
foodId the food ID itemFood the food item name foodPrice the food price receiptId the receipt ID
References es.ull.esit.app.middleware.model.MainCourse.foodId, es.ull.esit.app.middleware.model.MainCourse.foodPrice, es.ull.esit.app.middleware.model.MainCourse.itemFood, es.ull.esit.app.middleware.model.MainCourse.receiptId.
Long es.ull.esit.app.middleware.model.MainCourse.getFoodId()
Getters and Setters.
values of the attributes
References es.ull.esit.app.middleware.model.MainCourse.foodId.
void es.ull.esit.app.middleware.model.MainCourse.setFoodId(Long foodId)
Set food ID.
foodId the food ID
References es.ull.esit.app.middleware.model.MainCourse.foodId.
String es.ull.esit.app.middleware.model.MainCourse.getItemFood()
Get item food.
References es.ull.esit.app.middleware.model.MainCourse.itemFood.
Referenced by es.ull.esit.app.adminProducts.jTable3MouseClicked.
void es.ull.esit.app.middleware.model.MainCourse.setItemFood(String itemFood)
Set item food.
itemFood the food item name
References es.ull.esit.app.middleware.model.MainCourse.itemFood.
Integer es.ull.esit.app.middleware.model.MainCourse.getFoodPrice()
Get food price.
the food price
References es.ull.esit.app.middleware.model.MainCourse.foodPrice.
Referenced by es.ull.esit.app.adminProducts.jTable3MouseClicked.
void es.ull.esit.app.middleware.model.MainCourse.setFoodPrice(Integer foodPrice)
Set food price.
foodPrice the food price
References es.ull.esit.app.middleware.model.MainCourse.foodPrice.
Long es.ull.esit.app.middleware.model.MainCourse.getReceiptId()
Get receipt ID.
the receipt ID
References es.ull.esit.app.middleware.model.MainCourse.receiptId.
void es.ull.esit.app.middleware.model.MainCourse.setReceiptId(Long receiptId)
Set receipt ID.
receiptId the receipt ID
References es.ull.esit.app.middleware.model.MainCourse.receiptId.