package es.ull.esit.app;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.util.function.Supplier;

/**
 * @brief Login window for administrators.
 * 
 *        It is displayed after a successful login with role ADMIN.
 *        Shows a Swing form that lets administrators:
 *        - access to the product and price management window.
 *        - access to the general menu window used to place orders.
 *        - log out and return to the login window.
 */
public class AdminLogin extends javax.swing.JFrame {

  /** Primary font used in the UI components. */
  private static final String PRIMARY_FONT = "Yu Gothic UI";

  /** Logger for logging events and errors. */
  private static final Logger LOGGER = LoggerFactory.getLogger(AdminLogin.class);

  /**
   * @brief Factory (test seam) to create the product administration window.
   *
   *        Tests can override this supplier to inject a lightweight stub window
   *        and avoid opening real UI frames.
   */
  static Supplier<java.awt.Window> adminProductsSupplier = AdminProducts::new;

  /**
   * @brief Factory (test seam) to create the order/menu window.
   *
   *        Tests can override this supplier to avoid triggering real UI
   *        initialization or background loading.
   */
  static Supplier<java.awt.Window> orderSupplier = Order::new;

  /**
   * @brief Factory (test seam) to create the login window shown after logout.
   *
   *        Tests can override this supplier to prevent opening real UI windows.
   */
  static Supplier<java.awt.Window> loginSupplier = Login::new;

  /**
   * @brief Constructor.
   * 
   *        Creates the admin login window and initializes GUI components.
   */
  public AdminLogin() {
    initComponents();
  }

  /**
   * @brief Initializes GUI components.
   * 
   *        Generated by the Form Editor: do not modify.
   *        Sets up welcome label, logo image, buttons for "Update Prices",
   *        "Menu", and "LogOut" and the layout and configuration of the window.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  // GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jButton2 = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Admin ");
    setResizable(false);

    jPanel1.setBackground(new java.awt.Color(248, 244, 230));

    jLabel3.setFont(new java.awt.Font(PRIMARY_FONT, 1, 24)); // NOI18N
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel3.setText("Welcome Admin");

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/screenshot.png"))); // NOI18N

    jButton2.setBackground(new java.awt.Color(153, 153, 153));
    jButton2.setFont(new java.awt.Font(PRIMARY_FONT, 1, 18)); // NOI18N
    jButton2.setText("Update Prices");
    jButton2.addActionListener(this::jButton2ActionPerformed);

    jButton1.setBackground(new java.awt.Color(153, 153, 153));
    jButton1.setFont(new java.awt.Font(PRIMARY_FONT, 1, 18)); // NOI18N
    jButton1.setText("Menu");
    jButton1.addActionListener(this::jButton1ActionPerformed);

    jButton3.setFont(new java.awt.Font(PRIMARY_FONT, 1, 18)); // NOI18N
    jButton3.setText("LogOut");
    jButton3.addActionListener(this::jButton3ActionPerformed);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 320,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 320,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 306,
                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 141,
                            javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE)));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @brief Action handler for the "Update Prices" button.
   *        Actions steps:
   *        - Opens the product administration window to modify prices and
   *        products.
   *
   * @param evt [java.awt.event.ActionEvent] Action event triggered by button
   *            click.
   */
  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
    try {
      adminProductsSupplier.get().setVisible(true);
      this.dispose();
    } catch (Exception ex) {
      LOGGER.error("Error opening product admin window", ex);
      javax.swing.JOptionPane.showMessageDialog(
          this,
          "Error opening product admin window:\n" + ex.getMessage(),
          "Error",
          javax.swing.JOptionPane.ERROR_MESSAGE);
    }
  }// GEN-LAST:event_jButton2ActionPerformed

  /**
   * @brief Action handler for the "Menu" button.
   *        Actions steps:
   *        - Opens the general menu window to place orders.
   * 
   * @param evt [java.awt.event.ActionEvent] Action event triggered by button
   *            click.
   */
  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
    try {
      orderSupplier.get().setVisible(true);
      this.dispose();
    } catch (Exception ex) {
      LOGGER.error("Error opening menu window", ex);
      javax.swing.JOptionPane.showMessageDialog(
          this,
          "Error opening menu window:\n" + ex.getMessage(),
          "Error",
          javax.swing.JOptionPane.ERROR_MESSAGE);
    }
  }// GEN-LAST:event_jButton1ActionPerformed

  /**
   * @brief Action handler for the "LogOut" button.
   *        Actions steps:
   *        - Logs out the admin and returns to the login window.
   * 
   * @param evt [java.awt.event.ActionEvent] Action event triggered by button
   *            click.
   */
  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
    loginSupplier.get().setVisible(true);
    this.dispose();
  }// GEN-LAST:event_jButton3ActionPerformed

  /**
   * @brief Standalone entry point for testing the AdminLogin window.
   *
   *        Sets the Nimbus look and feel if available and shows an instance
   *        of AdminLogin. In the normal application flow this window is started
   *        from the Login class after a successful admin login.
   *
   * @param args [String[]] Command line arguments (not used).
   */
  public static void main(String[] args) {
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
        | javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    java.awt.EventQueue.invokeLater(() -> new AdminLogin().setVisible(true));
  }

  // Variables declaration - do not modify
  // GEN-BEGIN:variables
  // Sonarqube rule java:S1450 must be ignored here as these variables are
  // auto-generated by the Form Editor and need to remain as instance variables.
  /** Button that opens the main menu window. */
  private javax.swing.JButton jButton1;
  /** Button that opens the price management window. */
  private javax.swing.JButton jButton2;
  /** Button used to log out and return to the login screen. */
  private javax.swing.JButton jButton3;
  /** Label that displays the application logo or image. */
  private javax.swing.JLabel jLabel1;
  /** Label that displays the welcome text for the administrator. */
  private javax.swing.JLabel jLabel3;
  /** Main container panel for all UI elements. */
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}