package es.ull.esit.app;

import java.util.List;
import java.util.logging.Logger;

import es.ull.esit.app.middleware.model.Appetizer;

/**
 * @file Cashier.java
 * @brief UI for the project's cashier.
 *
 *        Window that allows the cashier to access information about the
 *        restaurant
 *        and the menu. Includes constructors to display the cashier's name.
 * 
 */
public class Cashier extends javax.swing.JFrame {

  // Added: client to communicate with the REST middleware
  private transient es.ull.esit.app.middleware.ApiClient api;

  /** Base URL for the backend API. */
  static final String BASE_URL = "http://localhost:8080";

  /** Principal font name used in the UI. */
  static final String PRINCIPAL_FONT_NAME = "Yu Gothic UI";

  /** Logger instance for logging purposes. */
  static final Logger logger = Logger.getLogger(Cashier.class.getName());

  /**
   * @brief Default constructor. Initializes the interface.
   */
  public Cashier() {
    this(new es.ull.esit.app.middleware.ApiClient(BASE_URL));
  }

  /**
   * @brief Constructor with cashier's name.
   *
   *        Displays a personalized welcome message.
   *
   * @param name name of the cashier who logged in
   */
  public Cashier(String name) {
    this(new es.ull.esit.app.middleware.ApiClient(BASE_URL), name);
  }

  /**
   * Constructor that receives an ApiClient and optionally the cashier's name.
   */
  public Cashier(es.ull.esit.app.middleware.ApiClient apiClient, String... optionalName) {
    initComponents();
    this.api = apiClient == null ? new es.ull.esit.app.middleware.ApiClient(BASE_URL) : apiClient;
    String name = (optionalName != null && optionalName.length > 0) ? optionalName[0] : null;
    if (name == null || name.isEmpty()) {
      welcomeTxt.setText("Welcome Cashier,");
    } else {
      welcomeTxt.setText("Welcome " + name);
    }
  }

  /**
   * @brief This method is called from within the constructor to initialize the
   *        form.
   *        WARNING: Do NOT modify this code. The content of this method is always
   *        regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
    welcomeTxt = new javax.swing.JLabel();
    javax.swing.JButton jButton1 = new javax.swing.JButton();
    javax.swing.JButton jButton2 = new javax.swing.JButton();
    javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
    javax.swing.JButton jButton3 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Cashier");
    setResizable(false);

    jPanel1.setBackground(new java.awt.Color(248, 244, 230));

    welcomeTxt.setFont(new java.awt.Font(PRINCIPAL_FONT_NAME, 1, 24)); // NOI18N
    welcomeTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    welcomeTxt.setText("Welcome Cashier");

    jButton1.setBackground(new java.awt.Color(153, 153, 153));
    jButton1.setFont(new java.awt.Font(PRINCIPAL_FONT_NAME, 1, 18)); // NOI18N
    jButton1.setText("About us");
    jButton1.addActionListener(this::jButton1ActionPerformed);

    jButton2.setBackground(new java.awt.Color(153, 153, 153));
    jButton2.setFont(new java.awt.Font(PRINCIPAL_FONT_NAME, 1, 18)); // NOI18N
    jButton2.setText("Menu");
    jButton2.addActionListener(this::jButton2ActionPerformed);

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/screenshot.png"))); // NOI18N

    jButton3.setBackground(new java.awt.Color(255, 255, 255));
    jButton3.setFont(new java.awt.Font(PRINCIPAL_FONT_NAME, 1, 18)); // NOI18N
    jButton3.setText("LogOut");
    jButton3.addActionListener(this::jButton3ActionPerformed);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 299,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 320,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(98, 98, 98))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(183, 183, 183))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 141,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(190, 190, 190)))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(108, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 320,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(99, 99, 99))));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(welcomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(290, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(242, 242, 242))));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @brief Button action to show information about the restaurant.
   *
   * @param evt action event of the button
   */
  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
    // If you want to show cashier info instead of generic info
    new Thread(() -> {
      try {
        // Example: get cashier data
        List<es.ull.esit.app.middleware.model.Cashier> cashiers = api.getAllCashiers();
        logger.info("Found " + cashiers.size() + " cashiers");
      } catch (Exception ex) {
        logger.severe("Error getting cashiers: " + ex.getMessage());
      }
      javax.swing.SwingUtilities.invokeLater(() -> {
        new AboutUs().setVisible(true);
        dispose();
      });
    }).start();
  }// GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
    // Load menu items using new CRUD methods
    new Thread(() -> {
      try {
        List<Appetizer> appetizers = api.getAllAppetizers();
        List<es.ull.esit.app.middleware.model.Drink> drinks = api.getAllDrinks();
        List<es.ull.esit.app.middleware.model.MainCourse> mainCourses = api.getAllMainCourses();

        logger.info("Menu loaded: " + appetizers.size() + " appetizers, " +
            drinks.size() + " drinks, " + mainCourses.size() + " main courses");
      } catch (Exception ex) {
        logger.severe("Error loading menu: " + ex.getMessage());
      }
      javax.swing.SwingUtilities.invokeLater(() -> {
        new OrderMenu().setVisible(true);
        dispose();
      });
    }).start();
  }// GEN-LAST:event_jButton2ActionPerformed

  /**
   * @brief Button action to log out and return to the login screen.
   *
   * @param evt action event of the button
   */
  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton3ActionPerformed
    // Optional: notify middleware of logout
    new Thread(() -> {
      try {
        // TODO -> IMPLEMENTAR LOGICA DE LOGIN Y LOGOUT
        // api.login(""); // simple ping/logout placeholder
      } catch (Exception ex) {
        // ignore
      }
      javax.swing.SwingUtilities.invokeLater(() -> {
        new Login().setVisible(true);
        dispose();
      });
    }).start();
  }// GEN-LAST:event_jButton3ActionPerformed

  /**
   * @brief Entry point to run this window independently.
   *
   * @param args command line arguments (not used)
   */
  public static void main(String[] args) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
        | javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new Cashier().setVisible(true));
  }

  private javax.swing.JLabel welcomeTxt;
}
