/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.ull.esit.app;

import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 * Ventana principal del menú del restaurante Black Plate.
 * 
 * Esta clase proporciona la interfaz gráfica completa para gestionar pedidos:
 * - Selección de productos por categorías (bebidas, aperitivos, platos principales)
 * - Personalización de platos (opciones picantes, ingredientes adicionales)
 * - Cálculo automático de precios, subtotales, IVA y totales
 * - Generación y guardado de recibos en archivos de texto
 * - Funcionalidad para crear nuevos pedidos y gestionar el carrito
 * 
 * El menú incluye:
 * - Bebidas: Cola, 7up, Mojito, Jugo de naranja
 * - Aperitivos: Papas Truffel, Chocolate fundido, Mac&Cheese Balls, Camarones Dynamite
 * - Platos principales: Pizza Buratta, Pasta Rosa, Salmón Rosemary, Spaghetti
 * 
 * Cada producto tiene un precio fijo y permite seleccionar cantidad (0-10 unidades).
 * El IVA se calcula al 15% sobre el subtotal.
 * 
 * @author Sistema de Gestión de Restaurante
 * @version 1.0
 */
public class Frame1 extends javax.swing.JFrame {
    // Cantidades seleccionadas para cada producto
    int colaNum , upNum, orangeNum, mojitoNum, friesNum, moltenNum, macNum, shrimpNum, pizzaNum, pastaNum, salmonNum, spaghettiNum; 
    
    // Precios calculados para cada producto según cantidad
    double cola_Price, up_Price, mojito_Price, orange_Price, molten_Price, mac_Price, fries_Price, shrimp_Price, pizza_Price,pasta_Price , salmon_Price, spaghetti_Price;
    
    // Precios unitarios fijos para cada producto (en SR - Saudi Riyal)
    final double colaCost=6.0, upCost=6.0, mojitoCost=14.0, orangeCost=10.0, moltenCost=28.0, macCost=39.0, friesCost=32.0, shrimpCost=42.0, pizzaCost=60.0,pastaCost=52.0, salmonCost=71.0, spaghettiCost=55.0;
    
    // Variables para el cálculo del total del pedido
    double subTotal,vat, total;
    
    // Número del recibo actual
    int receiptNo;
    
    // Objeto para escribir el recibo en un archivo
    PrintWriter output;

    /**
     * Constructor que crea e inicializa la ventana del menú.
     * 
     * Inicializa todos los componentes gráficos de la interfaz mediante
     * el método initComponents() generado por NetBeans Form Editor.
     */
    public Frame1() {
        initComponents();
    }
    
    /**
     * Método para cargar precios desde la base de datos (actualmente no implementado).
     * 
     * Este método está reservado para una funcionalidad futura que permitiría
     * cargar precios dinámicamente desde la base de datos en lugar de usar
     * precios fijos en constantes.
     */
   void loadPrice(){
   
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        DrinksPnl = new javax.swing.JPanel();
        colaLbl = new javax.swing.JLabel();
        upLbl = new javax.swing.JLabel();
        mojitoLbl = new javax.swing.JLabel();
        colaCountS = new javax.swing.JSpinner();
        upCountS = new javax.swing.JSpinner();
        mojitoCountS = new javax.swing.JSpinner();
        orangLbl = new javax.swing.JLabel();
        orangeCountS = new javax.swing.JSpinner();
        orangePriceLbl = new javax.swing.JLabel();
        upPriceLbl = new javax.swing.JLabel();
        colaPriceLbl = new javax.swing.JLabel();
        mojitoPriceLbl = new javax.swing.JLabel();
        AppetizerPnl = new javax.swing.JPanel();
        friesLbl = new javax.swing.JLabel();
        moltenLbl = new javax.swing.JLabel();
        shrimpLbl = new javax.swing.JLabel();
        friesCountS = new javax.swing.JSpinner();
        moltenCountS = new javax.swing.JSpinner();
        shrimpCountS = new javax.swing.JSpinner();
        macLbl = new javax.swing.JLabel();
        macCountS = new javax.swing.JSpinner();
        friesPriceLbl = new javax.swing.JLabel();
        moltenPriceLbl = new javax.swing.JLabel();
        macPriceLbl = new javax.swing.JLabel();
        shrimpPriceLbl = new javax.swing.JLabel();
        MainCoursePnl = new javax.swing.JPanel();
        pizzaLbl = new javax.swing.JLabel();
        pastaLbl = new javax.swing.JLabel();
        spaghettiLbl = new javax.swing.JLabel();
        pizzaCountS = new javax.swing.JSpinner();
        pastaCountS = new javax.swing.JSpinner();
        spaghettiCountS = new javax.swing.JSpinner();
        salmonLbl = new javax.swing.JLabel();
        salmonCountS = new javax.swing.JSpinner();
        pizzaPriceLbl = new javax.swing.JLabel();
        spaghettiPriceLbl = new javax.swing.JLabel();
        salmonPriceLbl = new javax.swing.JLabel();
        pastaPriceLbl = new javax.swing.JLabel();
        spaghettiSpicy = new javax.swing.JCheckBox();
        pizzaSpicy = new javax.swing.JCheckBox();
        pastaChicken = new javax.swing.JCheckBox();
        salmonRice = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        subTotalLbl = new javax.swing.JLabel();
        vatLbl = new javax.swing.JLabel();
        totalLbl = new javax.swing.JLabel();
        receiptNoLbl = new javax.swing.JLabel();
        payBtn = new javax.swing.JButton();
        newReceiptBtn = new javax.swing.JButton();
        saveReceiptBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        goBackMenueBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(248, 244, 230));

        DrinksPnl.setBackground(new java.awt.Color(248, 244, 230));
        DrinksPnl.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Drinks", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Yu Gothic UI", 0, 18))); // NOI18N
        DrinksPnl.setPreferredSize(new java.awt.Dimension(260, 278));

        colaLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        colaLbl.setText("Cola");

        upLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        upLbl.setText("7up");

        mojitoLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        mojitoLbl.setText("Mojito");

        colaCountS.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        colaCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        colaCountS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                colaCountSStateChanged(evt);
            }
        });

        upCountS.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        upCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        upCountS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                upCountSStateChanged(evt);
            }
        });

        mojitoCountS.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        mojitoCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        mojitoCountS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mojitoCountSStateChanged(evt);
            }
        });

        orangLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        orangLbl.setText("Orange juice");

        orangeCountS.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        orangeCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        orangeCountS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                orangeCountSStateChanged(evt);
            }
        });

        orangePriceLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        orangePriceLbl.setText("0.0 SR");

        upPriceLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        upPriceLbl.setText("0.0 SR");

        colaPriceLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        colaPriceLbl.setText("0.0 SR");

        mojitoPriceLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        mojitoPriceLbl.setText("0.0 SR");

        javax.swing.GroupLayout DrinksPnlLayout = new javax.swing.GroupLayout(DrinksPnl);
        DrinksPnl.setLayout(DrinksPnlLayout);
        DrinksPnlLayout.setHorizontalGroup(
            DrinksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrinksPnlLayout.createSequentialGroup()
                .addGroup(DrinksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DrinksPnlLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(colaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(colaCountS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(colaPriceLbl))
                    .addGroup(DrinksPnlLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(upLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(upCountS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(upPriceLbl))
                    .addGroup(DrinksPnlLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(orangLbl)
                        .addGap(12, 12, 12)
                        .addComponent(orangeCountS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(orangePriceLbl))
                    .addGroup(DrinksPnlLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(mojitoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(mojitoCountS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mojitoPriceLbl)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        DrinksPnlLayout.setVerticalGroup(
            DrinksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrinksPnlLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(DrinksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colaLbl)
                    .addGroup(DrinksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(colaPriceLbl)
                        .addComponent(colaCountS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(DrinksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upLbl)
                    .addGroup(DrinksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(upPriceLbl)
                        .addComponent(upCountS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(DrinksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orangLbl)
                    .addGroup(DrinksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(orangeCountS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(orangePriceLbl)))
                .addGroup(DrinksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DrinksPnlLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(mojitoLbl))
                    .addGroup(DrinksPnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DrinksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mojitoCountS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mojitoPriceLbl))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        AppetizerPnl.setBackground(new java.awt.Color(248, 244, 230));
        AppetizerPnl.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Appetizers", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Yu Gothic UI", 0, 18))); // NOI18N
        AppetizerPnl.setPreferredSize(new java.awt.Dimension(260, 278));

        friesLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        friesLbl.setText("Truffel Fries");

        moltenLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        moltenLbl.setText("Molten Chocolate");

        shrimpLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        shrimpLbl.setText("Dynamite Shrimp");

        friesCountS.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        friesCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        friesCountS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                friesCountSStateChanged(evt);
            }
        });

        moltenCountS.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        moltenCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        moltenCountS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                moltenCountSStateChanged(evt);
            }
        });

        shrimpCountS.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        shrimpCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        shrimpCountS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                shrimpCountSStateChanged(evt);
            }
        });

        macLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        macLbl.setText("Mac&Cheese Balls");

        macCountS.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        macCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        macCountS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                macCountSStateChanged(evt);
            }
        });

        friesPriceLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        friesPriceLbl.setText("0.0 SR");

        moltenPriceLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        moltenPriceLbl.setText("0.0 SR");

        macPriceLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        macPriceLbl.setText("0.0 SR");

        shrimpPriceLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        shrimpPriceLbl.setText("0.0 SR");

        javax.swing.GroupLayout AppetizerPnlLayout = new javax.swing.GroupLayout(AppetizerPnl);
        AppetizerPnl.setLayout(AppetizerPnlLayout);
        AppetizerPnlLayout.setHorizontalGroup(
            AppetizerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppetizerPnlLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(AppetizerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AppetizerPnlLayout.createSequentialGroup()
                        .addComponent(friesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(friesCountS, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(friesPriceLbl))
                    .addGroup(AppetizerPnlLayout.createSequentialGroup()
                        .addComponent(shrimpLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(shrimpCountS, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(shrimpPriceLbl))
                    .addGroup(AppetizerPnlLayout.createSequentialGroup()
                        .addComponent(moltenLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(moltenCountS, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(moltenPriceLbl))
                    .addGroup(AppetizerPnlLayout.createSequentialGroup()
                        .addComponent(macLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(macCountS, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(macPriceLbl)))
                .addContainerGap())
        );
        AppetizerPnlLayout.setVerticalGroup(
            AppetizerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppetizerPnlLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(AppetizerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(friesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AppetizerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(friesCountS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(friesPriceLbl)))
                .addGap(10, 10, 10)
                .addGroup(AppetizerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moltenLbl)
                    .addGroup(AppetizerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(moltenCountS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(moltenPriceLbl)))
                .addGroup(AppetizerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AppetizerPnlLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(macLbl))
                    .addGroup(AppetizerPnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AppetizerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(macPriceLbl)
                            .addComponent(macCountS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16)
                .addGroup(AppetizerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shrimpLbl)
                    .addGroup(AppetizerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(shrimpCountS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(shrimpPriceLbl)))
                .addContainerGap())
        );

        MainCoursePnl.setBackground(new java.awt.Color(248, 244, 230));
        MainCoursePnl.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Main Course", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Yu Gothic UI", 0, 18))); // NOI18N
        MainCoursePnl.setPreferredSize(new java.awt.Dimension(260, 278));

        pizzaLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        pizzaLbl.setText("Buratta Pizza");

        pastaLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        pastaLbl.setText("Pink Pasta");
        pastaLbl.setToolTipText("");

        spaghettiLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        spaghettiLbl.setText("Spaghetti");

        pizzaCountS.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        pizzaCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        pizzaCountS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pizzaCountSStateChanged(evt);
            }
        });

        pastaCountS.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        pastaCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        pastaCountS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pastaCountSStateChanged(evt);
            }
        });

        spaghettiCountS.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        spaghettiCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        spaghettiCountS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spaghettiCountSStateChanged(evt);
            }
        });

        salmonLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        salmonLbl.setText("Rosemary Salmon");

        salmonCountS.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        salmonCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        salmonCountS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                salmonCountSStateChanged(evt);
            }
        });

        pizzaPriceLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        pizzaPriceLbl.setText("0.0 SR");

        spaghettiPriceLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        spaghettiPriceLbl.setText("0.0 SR");

        salmonPriceLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        salmonPriceLbl.setText("0.0 SR");

        pastaPriceLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        pastaPriceLbl.setText("0.0 SR");

        spaghettiSpicy.setBackground(new java.awt.Color(255, 255, 255));
        spaghettiSpicy.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        spaghettiSpicy.setText("Spicy");
        spaghettiSpicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spaghettiSpicyActionPerformed(evt);
            }
        });

        pizzaSpicy.setBackground(new java.awt.Color(255, 255, 255));
        pizzaSpicy.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        pizzaSpicy.setText("Spicy");
        pizzaSpicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaSpicyActionPerformed(evt);
            }
        });

        pastaChicken.setBackground(new java.awt.Color(255, 255, 255));
        pastaChicken.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        pastaChicken.setText("Chicken");
        pastaChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastaChickenActionPerformed(evt);
            }
        });

        salmonRice.setBackground(new java.awt.Color(255, 255, 255));
        salmonRice.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        salmonRice.setText("Rice");
        salmonRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salmonRiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainCoursePnlLayout = new javax.swing.GroupLayout(MainCoursePnl);
        MainCoursePnl.setLayout(MainCoursePnlLayout);
        MainCoursePnlLayout.setHorizontalGroup(
            MainCoursePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainCoursePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainCoursePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pizzaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainCoursePnlLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(MainCoursePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spaghettiLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pastaLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salmonLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainCoursePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainCoursePnlLayout.createSequentialGroup()
                                .addComponent(pizzaCountS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(MainCoursePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MainCoursePnlLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pizzaSpicy)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainCoursePnlLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(MainCoursePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(salmonRice)
                                            .addComponent(pastaChicken)
                                            .addComponent(spaghettiSpicy))
                                        .addGap(18, 18, 18)))
                                .addComponent(pizzaPriceLbl))
                            .addGroup(MainCoursePnlLayout.createSequentialGroup()
                                .addGroup(MainCoursePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(spaghettiCountS, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(salmonCountS, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pastaCountS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(MainCoursePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pastaPriceLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(salmonPriceLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(spaghettiPriceLbl, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        MainCoursePnlLayout.setVerticalGroup(
            MainCoursePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainCoursePnlLayout.createSequentialGroup()
                .addGroup(MainCoursePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainCoursePnlLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(pizzaPriceLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pastaPriceLbl)
                        .addGap(13, 13, 13))
                    .addGroup(MainCoursePnlLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(MainCoursePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainCoursePnlLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(pizzaLbl))
                            .addGroup(MainCoursePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pizzaSpicy)
                                .addComponent(pizzaCountS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(MainCoursePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainCoursePnlLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(MainCoursePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pastaLbl)
                                    .addComponent(pastaCountS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(MainCoursePnlLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pastaChicken)))
                        .addGap(1, 1, 1)))
                .addGroup(MainCoursePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salmonLbl)
                    .addComponent(salmonCountS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salmonPriceLbl)
                    .addComponent(salmonRice))
                .addGroup(MainCoursePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainCoursePnlLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(MainCoursePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spaghettiLbl)
                            .addGroup(MainCoursePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(spaghettiSpicy)
                                .addComponent(spaghettiCountS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(MainCoursePnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spaghettiPriceLbl)))
                .addGap(8, 8, 8))
        );

        jPanel1.setBackground(new java.awt.Color(248, 244, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Receipt", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Yu Gothic UI", 0, 14))); // NOI18N

        subTotalLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        subTotalLbl.setText("SubTotal: 0.0 SR");

        vatLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        vatLbl.setText("VAT included: 0.0 SR");

        totalLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        totalLbl.setText("Total: 0.0 SR");

        receiptNoLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        receiptNoLbl.setText("Receipt No. : 0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalLbl)
                            .addComponent(subTotalLbl))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(vatLbl)
                        .addGap(0, 108, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(receiptNoLbl)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subTotalLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vatLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(receiptNoLbl))
        );

        payBtn.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        payBtn.setText("Pay");
        payBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBtnActionPerformed(evt);
            }
        });

        newReceiptBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        newReceiptBtn.setText("New Receipt");
        newReceiptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newReceiptBtnActionPerformed(evt);
            }
        });

        saveReceiptBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        saveReceiptBtn.setText("Save Receipt");
        saveReceiptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveReceiptBtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 153, 0));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BLACK PLATE MENU");

        goBackMenueBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        goBackMenueBtn.setText("Go Back");
        goBackMenueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackMenueBtnActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/screenshot.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(goBackMenueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                                .addComponent(payBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saveReceiptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newReceiptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(AppetizerPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(MainCoursePnl, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(DrinksPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AppetizerPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(MainCoursePnl, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(DrinksPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(goBackMenueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(payBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(newReceiptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saveReceiptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void colaCountSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_colaCountSStateChanged
        // Actualiza la cantidad y precio de Cola cuando cambia el selector
        colaNum =(Integer) colaCountS.getValue();
        cola_Price=colaCost*colaNum;
        colaPriceLbl.setText(cola_Price+ " SR");

    }//GEN-LAST:event_colaCountSStateChanged

    private void upCountSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_upCountSStateChanged
        // Actualiza la cantidad y precio de 7up cuando cambia el selector
        upNum =(Integer) upCountS.getValue();
        up_Price=upCost*upNum;
        upPriceLbl.setText(up_Price+ " SR");

    }//GEN-LAST:event_upCountSStateChanged

    private void mojitoCountSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mojitoCountSStateChanged
        // Actualiza la cantidad y precio de Mojito cuando cambia el selector
        mojitoNum =(Integer) mojitoCountS.getValue();
        mojito_Price=mojitoCost*mojitoNum;
        mojitoPriceLbl.setText(mojito_Price+ " SR");
    }//GEN-LAST:event_mojitoCountSStateChanged

    private void orangeCountSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_orangeCountSStateChanged
        // Actualiza la cantidad y precio de Jugo de naranja cuando cambia el selector
        orangeNum =(Integer) orangeCountS.getValue();
        orange_Price=orangeCost*orangeNum;
        orangePriceLbl.setText(orange_Price+ " SR");
    }//GEN-LAST:event_orangeCountSStateChanged

    private void friesCountSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_friesCountSStateChanged
        // Actualiza la cantidad y precio de Papas Truffel cuando cambia el selector
        friesNum =(Integer) friesCountS.getValue();
        fries_Price=friesCost*friesNum;
        friesPriceLbl.setText(fries_Price+ " SR");
    }//GEN-LAST:event_friesCountSStateChanged

    private void moltenCountSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_moltenCountSStateChanged
        // Actualiza la cantidad y precio de Chocolate fundido cuando cambia el selector
        moltenNum =(Integer) moltenCountS.getValue();
        molten_Price=moltenCost*moltenNum;
        moltenPriceLbl.setText(molten_Price+ " SR");
    }//GEN-LAST:event_moltenCountSStateChanged

    private void shrimpCountSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_shrimpCountSStateChanged
        // Actualiza la cantidad y precio de Camarones Dynamite cuando cambia el selector
        shrimpNum =(Integer) shrimpCountS.getValue();
        shrimp_Price=shrimpCost*shrimpNum;
        shrimpPriceLbl.setText(shrimp_Price+ " SR");
    }//GEN-LAST:event_shrimpCountSStateChanged

    private void macCountSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_macCountSStateChanged
        // Actualiza la cantidad y precio de Mac&Cheese Balls cuando cambia el selector
        macNum =(Integer) macCountS.getValue();
        mac_Price=macCost*macNum;
        macPriceLbl.setText(mac_Price+ " SR");
    }//GEN-LAST:event_macCountSStateChanged

    private void pizzaCountSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pizzaCountSStateChanged
        // Actualiza la cantidad y precio de Pizza Buratta cuando cambia el selector
        pizzaNum =(Integer) pizzaCountS.getValue();
        pizza_Price=pizzaCost*pizzaNum;
        pizzaPriceLbl.setText(pizza_Price+ " SR");
    }//GEN-LAST:event_pizzaCountSStateChanged

    private void pastaCountSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pastaCountSStateChanged
        // Actualiza la cantidad y precio de Pasta Rosa cuando cambia el selector
        pastaNum =(Integer) pastaCountS.getValue();
        pasta_Price=pastaCost*pastaNum;
        pastaPriceLbl.setText(pasta_Price+ " SR");
    }//GEN-LAST:event_pastaCountSStateChanged

    private void spaghettiCountSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spaghettiCountSStateChanged
        // Actualiza la cantidad y precio de Spaghetti cuando cambia el selector
        spaghettiNum =(Integer) spaghettiCountS.getValue();
        spaghetti_Price=spaghettiCost*spaghettiNum;
        spaghettiPriceLbl.setText(spaghetti_Price+ " SR");
    }//GEN-LAST:event_spaghettiCountSStateChanged

    private void salmonCountSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_salmonCountSStateChanged
        // Actualiza la cantidad y precio de Salmón Rosemary cuando cambia el selector
        salmonNum =(Integer) salmonCountS.getValue();
        salmon_Price=salmonCost*salmonNum;
        salmonPriceLbl.setText(salmon_Price+ " SR");
    }//GEN-LAST:event_salmonCountSStateChanged

    private void spaghettiSpicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spaghettiSpicyActionPerformed
        // Agrega o quita 1 SR por cada unidad de spaghetti al seleccionar/deseleccionar la opción picante
        if(spaghettiSpicy.isSelected()){
            spaghetti_Price+=spaghettiNum;
        }else{
            spaghetti_Price-=spaghettiNum;
        }
        spaghettiPriceLbl.setText(spaghetti_Price+ " SR");
    }//GEN-LAST:event_spaghettiSpicyActionPerformed

    private void pizzaSpicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaSpicyActionPerformed
        // Agrega o quita 1 SR por cada unidad de pizza al seleccionar/deseleccionar la opción picante
        if(pizzaSpicy.isSelected()){
            pizza_Price+=pizzaNum;
        }else{
            pizza_Price-=pizzaNum;
        }
        pizzaPriceLbl.setText(pizza_Price+ " SR");
    }//GEN-LAST:event_pizzaSpicyActionPerformed

    private void pastaChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastaChickenActionPerformed
        // Agrega o quita 1 SR por cada unidad de pasta al seleccionar/deseleccionar la opción de pollo
        if(pastaChicken.isSelected()){
            pasta_Price+=pastaNum;
        }else{
            pasta_Price-=pastaNum;
        }
        pastaPriceLbl.setText(pasta_Price+ " SR");
    }//GEN-LAST:event_pastaChickenActionPerformed

    private void salmonRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salmonRiceActionPerformed
        // Agrega o quita 1 SR por cada unidad de salmón al seleccionar/deseleccionar la opción de arroz
        if(salmonRice.isSelected()){
            salmon_Price+=salmonNum;
        }else{
            salmon_Price-=salmonNum;
        }
        salmonPriceLbl.setText(salmon_Price+ " SR");
    }//GEN-LAST:event_salmonRiceActionPerformed

    private void payBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBtnActionPerformed
        // Calcula el subtotal sumando todos los precios de los productos seleccionados
        subTotal=cola_Price+up_Price+ mojito_Price+ orange_Price+ molten_Price+ mac_Price+ fries_Price+ shrimp_Price+ pizza_Price+pasta_Price + salmon_Price+ spaghetti_Price;

        subTotalLbl.setText("SubTotal "+subTotal+" SR");

        // Calcula el IVA (15% del subtotal)
        vat=subTotal*0.15;
        vatLbl.setText("VAT included "+vat+" SR");

        // Calcula el total sumando subtotal + IVA
        total=subTotal+vat;
        totalLbl.setText("Total "+total+" SR");

        // Valida que se haya seleccionado al menos un producto antes de procesar el pago
        if (subTotal==0){
            JOptionPane.showMessageDialog(null,"Please select an item first!",null,JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null,"Paid successfully");
        }
    }//GEN-LAST:event_payBtnActionPerformed

    private void saveReceiptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveReceiptBtnActionPerformed
        // Guarda el recibo actual en un archivo de texto en la carpeta "receipts"
        try {

            if (total != 0) {
         // Crea un archivo con el nombre basado en el número de recibo
           output = new PrintWriter("receipts/billNo." + receiptNo + ".txt");

           // Muestra mensaje de confirmación
          JOptionPane.showMessageDialog(null, "Recipt number: " + receiptNo + "  has been saved successfuly" + "");
               
                // Escribe la información del recibo en el archivo
            output.println(" Bill number is: " + receiptNo);
                output.println("==============");
                output.println("--------------");
                output.println("Subtotal is: " + subTotal + " SR");
                output.println("vat: " + vat + " SR");
                output.println("Total is: " + total + " SR");
                output.println();
                output.println("THANK YOU FOR ORDERING");

   
            }
                          output.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Error occured. Please try again");

        }
    }//GEN-LAST:event_saveReceiptBtnActionPerformed

    private void newReceiptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newReceiptBtnActionPerformed
        // Reinicia el formulario para crear un nuevo pedido (solo si ya se procesó un pago)
        if (total!=0){
            // Reinicia todos los selectores de cantidad a 0
            colaCountS.setValue(0);
            upCountS.setValue(0);
            orangeCountS.setValue(0);
            mojitoCountS.setValue(0);

            friesCountS.setValue(0);
            moltenCountS.setValue(0);
            macCountS.setValue(0);
            shrimpCountS.setValue(0);

            pizzaCountS.setValue(0);
            pastaCountS.setValue(0);
            salmonCountS.setValue(0);
            spaghettiCountS.setValue(0);

            // Deselecciona todas las opciones adicionales (checkboxes)
            pizzaSpicy.setSelected(false);
            pastaChicken.setSelected(false);
            salmonRice.setSelected(false);
            spaghettiSpicy.setSelected(false);

            // Reinicia las etiquetas de totales
            subTotalLbl.setText("SubTotal : 0.0 SR");
            vatLbl.setText("VAT included : 0.0 SR");
            totalLbl.setText("Total : 0.0 SR");

            // Reinicia las variables de cálculo
            subTotal=0;
            vat=0;
            total=0;

            // Incrementa el número de recibo para el siguiente pedido
            receiptNo++;
            receiptNoLbl.setText("ReceiptNo. :"+receiptNo);

        }
    }//GEN-LAST:event_newReceiptBtnActionPerformed

    private void goBackMenueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackMenueBtnActionPerformed
        // Cierra la ventana actual y regresa a la pantalla de login
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_goBackMenueBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AppetizerPnl;
    private javax.swing.JPanel DrinksPnl;
    private javax.swing.JPanel MainCoursePnl;
    private javax.swing.JSpinner colaCountS;
    private javax.swing.JLabel colaLbl;
    private javax.swing.JLabel colaPriceLbl;
    private javax.swing.JSpinner friesCountS;
    private javax.swing.JLabel friesLbl;
    private javax.swing.JLabel friesPriceLbl;
    private javax.swing.JButton goBackMenueBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner macCountS;
    private javax.swing.JLabel macLbl;
    private javax.swing.JLabel macPriceLbl;
    private javax.swing.JSpinner mojitoCountS;
    private javax.swing.JLabel mojitoLbl;
    private javax.swing.JLabel mojitoPriceLbl;
    private javax.swing.JSpinner moltenCountS;
    private javax.swing.JLabel moltenLbl;
    private javax.swing.JLabel moltenPriceLbl;
    private javax.swing.JButton newReceiptBtn;
    private javax.swing.JLabel orangLbl;
    private javax.swing.JSpinner orangeCountS;
    private javax.swing.JLabel orangePriceLbl;
    private javax.swing.JCheckBox pastaChicken;
    private javax.swing.JSpinner pastaCountS;
    private javax.swing.JLabel pastaLbl;
    private javax.swing.JLabel pastaPriceLbl;
    private javax.swing.JButton payBtn;
    private javax.swing.JSpinner pizzaCountS;
    private javax.swing.JLabel pizzaLbl;
    private javax.swing.JLabel pizzaPriceLbl;
    private javax.swing.JCheckBox pizzaSpicy;
    private javax.swing.JLabel receiptNoLbl;
    private javax.swing.JSpinner salmonCountS;
    private javax.swing.JLabel salmonLbl;
    private javax.swing.JLabel salmonPriceLbl;
    private javax.swing.JCheckBox salmonRice;
    private javax.swing.JButton saveReceiptBtn;
    private javax.swing.JSpinner shrimpCountS;
    private javax.swing.JLabel shrimpLbl;
    private javax.swing.JLabel shrimpPriceLbl;
    private javax.swing.JSpinner spaghettiCountS;
    private javax.swing.JLabel spaghettiLbl;
    private javax.swing.JLabel spaghettiPriceLbl;
    private javax.swing.JCheckBox spaghettiSpicy;
    private javax.swing.JLabel subTotalLbl;
    private javax.swing.JLabel totalLbl;
    private javax.swing.JSpinner upCountS;
    private javax.swing.JLabel upLbl;
    private javax.swing.JLabel upPriceLbl;
    private javax.swing.JLabel vatLbl;
    // End of variables declaration//GEN-END:variables
}
