/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.ull.esit.app;

import es.ull.esit.app.middleware.ApiClient;
import es.ull.esit.app.middleware.model.Appetizer;
import es.ull.esit.app.middleware.model.BillResult;
import es.ull.esit.app.middleware.model.Drink;
import es.ull.esit.app.middleware.model.MainCourse;
import es.ull.esit.app.middleware.service.OrderService;
import es.ull.esit.app.middleware.service.ProductService;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 * @file Frame1.java
 * @brief Main menu window and receipt management (order UI).
 *
 * Now decoupled from logic:
 * - Uses ProductService to fetch REAL prices from the database.
 * - Uses OrderService to calculate totals and save files.
 */
public class Frame1 extends javax.swing.JFrame {
    
    // Services
    private final ProductService productService;
    private final OrderService orderService;

    /** Counters for selected quantity per product. */
    int colaNum, upNum, orangeNum, mojitoNum, friesNum, moltenNum, macNum, shrimpNum, pizzaNum, pastaNum, salmonNum,
            spaghettiNum;
    
    /** Calculated total price per product (quantity * unit cost). */
    double cola_Price, up_Price, mojito_Price, orange_Price, molten_Price, mac_Price, fries_Price, shrimp_Price,
            pizza_Price, pasta_Price, salmon_Price, spaghetti_Price;
    
    /** * DYNAMIC PRICE MAP.
     * Instead of hardcoded constants, we store prices loaded from the DB here.
     * Key: Product Name (e.g., "Cola"), Value: Price
     */
    private Map<String, Double> prices = new HashMap<>();

    /** Totals and derived values. */
    double subTotal, vat, total;
    
    /** Current receipt number. */
    int receiptNo;

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
        
        // Initialize Services
        ApiClient client = new ApiClient("http://localhost:8080");
        this.productService = new ProductService(client);
        this.orderService = new OrderService();
        
        // Initialize default prices (fallback in case DB is empty)
        initDefaultPrices();
        
        // Load REAL prices from Backend
        loadLivePrices();
    }

    /** Sets fallback prices to ensure the UI works even if offline. */
    private void initDefaultPrices() {
        prices.put("Cola", 6.0);
        prices.put("7up", 6.0);
        prices.put("Mojito", 14.0);
        prices.put("Orange juice", 10.0);
        prices.put("Truffel Fries", 32.0);
        prices.put("Molten Chocolate", 28.0);
        prices.put("Mac&Cheese Balls", 39.0);
        prices.put("Dynamite Shrimp", 42.0);
        prices.put("Buratta Pizza", 60.0);
        prices.put("Pink Pasta", 52.0);
        prices.put("Rosemary Salmon", 71.0);
        prices.put("Spaghetti", 55.0);
    }

    /**
     * Fetches current prices from the API and updates the map.
     */
    private void loadLivePrices() {
        new Thread(() -> {
            try {
                List<Drink> drinks = productService.getAllDrinks();
                // FIX: (double) Cast hinzugefügt
                for (Drink d : drinks) {
                    prices.put(d.getItemDrinks(), (double) d.getDrinksPrice());
                }

                List<Appetizer> apps = productService.getAllAppetizers();
                // FIX: (double) Cast hinzugefügt
                for (Appetizer a : apps) {
                    prices.put(a.getItemAppetizers(), (double) a.getAppetizersPrice());
                }

                List<MainCourse> mains = productService.getAllMainCourses();
                // FIX: (double) Cast hinzugefügt
                for (MainCourse m : mains) {
                    prices.put(m.getItemFood(), (double) m.getFoodPrice());
                }
                
                System.out.println("Prices updated from Database!");
                
            } catch (Exception e) {
                System.err.println("Could not load live prices: " + e.getMessage());
                // We silently fail and keep using default prices
            }
        }).start();
    }
    
    /** * Helper to safely get a price. 
     * If the exact name isn't in the DB, returns 0.0 to avoid crashes.
     */
    private double getPrice(String itemName) {
        return prices.getOrDefault(itemName, 0.0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        // ... (GUI CODE - PLEASE PASTE YOUR ORIGINAL GUI CODE HERE) ...
        // I am omitting the 500 lines of GUI initialization to keep the response clean.
        // Since you just want to copy-paste, you can keep your existing initComponents() 
        // exactly as it was. The Logic happens in the ActionListeners below.
        
        // PLACEHOLDER FOR COMPILATION
        jPanel2 = new javax.swing.JPanel();
        DrinksPnl = new javax.swing.JPanel();
        colaLbl = new javax.swing.JLabel();
        upLbl = new javax.swing.JLabel();
        mojitoLbl = new javax.swing.JLabel();
        colaCountS = new javax.swing.JSpinner();
        upCountS = new javax.swing.JSpinner();
        mojitoCountS = new javax.swing.JSpinner();
        orangLbl = new javax.swing.JLabel();
        orangeCountS = new javax.swing.JSpinner();
        orangePriceLbl = new javax.swing.JLabel();
        upPriceLbl = new javax.swing.JLabel();
        colaPriceLbl = new javax.swing.JLabel();
        mojitoPriceLbl = new javax.swing.JLabel();
        AppetizerPnl = new javax.swing.JPanel();
        friesLbl = new javax.swing.JLabel();
        moltenLbl = new javax.swing.JLabel();
        shrimpLbl = new javax.swing.JLabel();
        friesCountS = new javax.swing.JSpinner();
        moltenCountS = new javax.swing.JSpinner();
        shrimpCountS = new javax.swing.JSpinner();
        macLbl = new javax.swing.JLabel();
        macCountS = new javax.swing.JSpinner();
        friesPriceLbl = new javax.swing.JLabel();
        moltenPriceLbl = new javax.swing.JLabel();
        macPriceLbl = new javax.swing.JLabel();
        shrimpPriceLbl = new javax.swing.JLabel();
        MainCoursePnl = new javax.swing.JPanel();
        pizzaLbl = new javax.swing.JLabel();
        pastaLbl = new javax.swing.JLabel();
        spaghettiLbl = new javax.swing.JLabel();
        pizzaCountS = new javax.swing.JSpinner();
        pastaCountS = new javax.swing.JSpinner();
        spaghettiCountS = new javax.swing.JSpinner();
        salmonLbl = new javax.swing.JLabel();
        salmonCountS = new javax.swing.JSpinner();
        pizzaPriceLbl = new javax.swing.JLabel();
        spaghettiPriceLbl = new javax.swing.JLabel();
        salmonPriceLbl = new javax.swing.JLabel();
        pastaPriceLbl = new javax.swing.JLabel();
        spaghettiSpicy = new javax.swing.JCheckBox();
        pizzaSpicy = new javax.swing.JCheckBox();
        pastaChicken = new javax.swing.JCheckBox();
        salmonRice = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        subTotalLbl = new javax.swing.JLabel();
        vatLbl = new javax.swing.JLabel();
        totalLbl = new javax.swing.JLabel();
        receiptNoLbl = new javax.swing.JLabel();
        payBtn = new javax.swing.JButton();
        newReceiptBtn = new javax.swing.JButton();
        saveReceiptBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        goBackMenueBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);
        // ... (Imagine the rest of your GUI code here) ...
        // ...
        
        // This is just to make the code below compile for you to see the logic structure
        pack(); 
    }// </editor-fold>//GEN-END:initComponents

    // =========================================================================
    // EVENT HANDLERS (LOGIC REFACTORED TO USE DYNAMIC PRICES)
    // =========================================================================

    private void colaCountSStateChanged(javax.swing.event.ChangeEvent evt) {
        colaNum = (Integer) colaCountS.getValue();
        // Use getPrice() instead of hardcoded constant
        cola_Price = getPrice("Cola") * colaNum; 
        colaPriceLbl.setText(cola_Price + " SR");
    }

    private void upCountSStateChanged(javax.swing.event.ChangeEvent evt) {
        upNum = (Integer) upCountS.getValue();
        up_Price = getPrice("7up") * upNum;
        upPriceLbl.setText(up_Price + " SR");
    }

    private void mojitoCountSStateChanged(javax.swing.event.ChangeEvent evt) {
        mojitoNum = (Integer) mojitoCountS.getValue();
        mojito_Price = getPrice("Mojito") * mojitoNum;
        mojitoPriceLbl.setText(mojito_Price + " SR");
    }

    private void orangeCountSStateChanged(javax.swing.event.ChangeEvent evt) {
        orangeNum = (Integer) orangeCountS.getValue();
        orange_Price = getPrice("Orange juice") * orangeNum;
        orangePriceLbl.setText(orange_Price + " SR");
    }

    private void friesCountSStateChanged(javax.swing.event.ChangeEvent evt) {
        friesNum = (Integer) friesCountS.getValue();
        fries_Price = getPrice("Truffel Fries") * friesNum;
        friesPriceLbl.setText(fries_Price + " SR");
    }

    private void moltenCountSStateChanged(javax.swing.event.ChangeEvent evt) {
        moltenNum = (Integer) moltenCountS.getValue();
        molten_Price = getPrice("Molten Chocolate") * moltenNum;
        moltenPriceLbl.setText(molten_Price + " SR");
    }

    private void shrimpCountSStateChanged(javax.swing.event.ChangeEvent evt) {
        shrimpNum = (Integer) shrimpCountS.getValue();
        shrimp_Price = getPrice("Dynamite Shrimp") * shrimpNum;
        shrimpPriceLbl.setText(shrimp_Price + " SR");
    }

    private void macCountSStateChanged(javax.swing.event.ChangeEvent evt) {
        macNum = (Integer) macCountS.getValue();
        mac_Price = getPrice("Mac&Cheese Balls") * macNum;
        macPriceLbl.setText(mac_Price + " SR");
    }

    private void pizzaCountSStateChanged(javax.swing.event.ChangeEvent evt) {
        pizzaNum = (Integer) pizzaCountS.getValue();
        pizza_Price = getPrice("Buratta Pizza") * pizzaNum;
        pizzaPriceLbl.setText(pizza_Price + " SR");
    }

    private void pastaCountSStateChanged(javax.swing.event.ChangeEvent evt) {
        pastaNum = (Integer) pastaCountS.getValue();
        pasta_Price = getPrice("Pink Pasta") * pastaNum;
        pastaPriceLbl.setText(pasta_Price + " SR");
    }

    private void spaghettiCountSStateChanged(javax.swing.event.ChangeEvent evt) {
        spaghettiNum = (Integer) spaghettiCountS.getValue();
        spaghetti_Price = getPrice("Spaghetti") * spaghettiNum;
        spaghettiPriceLbl.setText(spaghetti_Price + " SR");
    }

    private void salmonCountSStateChanged(javax.swing.event.ChangeEvent evt) {
        salmonNum = (Integer) salmonCountS.getValue();
        salmon_Price = getPrice("Rosemary Salmon") * salmonNum;
        salmonPriceLbl.setText(salmon_Price + " SR");
    }

    // CHECKBOXES - Note: logic kept simple here, ideally extras should be priced in DB too
    
    private void spaghettiSpicyActionPerformed(java.awt.event.ActionEvent evt) {
        if (spaghettiSpicy.isSelected()) {
            spaghetti_Price += spaghettiNum;
        } else {
            spaghetti_Price -= spaghettiNum;
        }
        spaghettiPriceLbl.setText(spaghetti_Price + " SR");
    }

    private void pizzaSpicyActionPerformed(java.awt.event.ActionEvent evt) {
        if (pizzaSpicy.isSelected()) {
            pizza_Price += pizzaNum;
        } else {
            pizza_Price -= pizzaNum;
        }
        pizzaPriceLbl.setText(pizza_Price + " SR");
    }

    private void pastaChickenActionPerformed(java.awt.event.ActionEvent evt) {
        if (pastaChicken.isSelected()) {
            pasta_Price += pastaNum;
        } else {
            pasta_Price -= pastaNum;
        }
        pastaPriceLbl.setText(pasta_Price + " SR");
    }

    private void salmonRiceActionPerformed(java.awt.event.ActionEvent evt) {
        if (salmonRice.isSelected()) {
            salmon_Price += salmonNum;
        } else {
            salmon_Price -= salmonNum;
        }
        salmonPriceLbl.setText(salmon_Price + " SR");
    }

    // =========================================================================
    // PAY & SAVE LOGIC (DELEGATED TO SERVICE)
    // =========================================================================

    private void payBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // 1. Calculate raw sum of all current lines
        double itemsSum = cola_Price + up_Price + mojito_Price + orange_Price + molten_Price + mac_Price + fries_Price
                + shrimp_Price + pizza_Price + pasta_Price + salmon_Price + spaghetti_Price;

        if (itemsSum == 0) {
            JOptionPane.showMessageDialog(null, "Please select an item first!", null, JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // 2. Delegate calculation to Service
        BillResult bill = orderService.calculateBill(itemsSum);
        
        // 3. Update State & UI
        this.subTotal = bill.getSubTotal();
        this.vat = bill.getVat();
        this.total = bill.getTotal();

        subTotalLbl.setText("SubTotal " + subTotal + " SR");
        vatLbl.setText("VAT included " + vat + " SR");
        totalLbl.setText("Total " + total + " SR");

        JOptionPane.showMessageDialog(null, "Paid successfully");
    }

    private void saveReceiptBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (total == 0) {
            JOptionPane.showMessageDialog(null, "Total is 0. Please pay first.");
            return;
        }

        new Thread(() -> {
            try {
                // Delegate File I/O to Service
                BillResult currentBill = new BillResult(subTotal, vat, total);
                orderService.generateReceiptFile(receiptNo, currentBill);
                
                SwingUtilities.invokeLater(() -> 
                    JOptionPane.showMessageDialog(null, "Receipt number: " + receiptNo + " has been saved successfully")
                );
            } catch (Exception ex) {
                SwingUtilities.invokeLater(() -> 
                    JOptionPane.showMessageDialog(null, "Error saving receipt: " + ex.getMessage())
                );
            }
        }).start();
    }

    private void newReceiptBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (total != 0) {
            // Reset UI Components
            colaCountS.setValue(0);
            upCountS.setValue(0);
            orangeCountS.setValue(0);
            mojitoCountS.setValue(0);
            friesCountS.setValue(0);
            moltenCountS.setValue(0);
            macCountS.setValue(0);
            shrimpCountS.setValue(0);
            pizzaCountS.setValue(0);
            pastaCountS.setValue(0);
            salmonCountS.setValue(0);
            spaghettiCountS.setValue(0);

            pizzaSpicy.setSelected(false);
            pastaChicken.setSelected(false);
            salmonRice.setSelected(false);
            spaghettiSpicy.setSelected(false);

            subTotalLbl.setText("SubTotal : 0.0 SR");
            vatLbl.setText("VAT included : 0.0 SR");
            totalLbl.setText("Total : 0.0 SR");

            // Reset Internal State
            subTotal = 0;
            vat = 0;
            total = 0;

            receiptNo++;
            receiptNoLbl.setText("ReceiptNo. :" + receiptNo);
        }
    }

    private void goBackMenueBtnActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
        new Login().setVisible(true);
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Frame1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AppetizerPnl;
    private javax.swing.JPanel DrinksPnl;
    private javax.swing.JPanel MainCoursePnl;
    private javax.swing.JSpinner colaCountS;
    private javax.swing.JLabel colaLbl;
    private javax.swing.JLabel colaPriceLbl;
    private javax.swing.JSpinner friesCountS;
    private javax.swing.JLabel friesLbl;
    private javax.swing.JLabel friesPriceLbl;
    private javax.swing.JButton goBackMenueBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner macCountS;
    private javax.swing.JLabel macLbl;
    private javax.swing.JLabel macPriceLbl;
    private javax.swing.JSpinner mojitoCountS;
    private javax.swing.JLabel mojitoLbl;
    private javax.swing.JLabel mojitoPriceLbl;
    private javax.swing.JSpinner moltenCountS;
    private javax.swing.JLabel moltenLbl;
    private javax.swing.JLabel moltenPriceLbl;
    private javax.swing.JButton newReceiptBtn;
    private javax.swing.JLabel orangLbl;
    private javax.swing.JSpinner orangeCountS;
    private javax.swing.JLabel orangePriceLbl;
    private javax.swing.JCheckBox pastaChicken;
    private javax.swing.JSpinner pastaCountS;
    private javax.swing.JLabel pastaLbl;
    private javax.swing.JLabel pastaPriceLbl;
    private javax.swing.JButton payBtn;
    private javax.swing.JSpinner pizzaCountS;
    private javax.swing.JLabel pizzaLbl;
    private javax.swing.JLabel pizzaPriceLbl;
    private javax.swing.JCheckBox pizzaSpicy;
    private javax.swing.JLabel receiptNoLbl;
    private javax.swing.JSpinner salmonCountS;
    private javax.swing.JLabel salmonLbl;
    private javax.swing.JLabel salmonPriceLbl;
    private javax.swing.JCheckBox salmonRice;
    private javax.swing.JButton saveReceiptBtn;
    private javax.swing.JSpinner shrimpCountS;
    private javax.swing.JLabel shrimpLbl;
    private javax.swing.JLabel shrimpPriceLbl;
    private javax.swing.JSpinner spaghettiCountS;
    private javax.swing.JLabel spaghettiLbl;
    private javax.swing.JLabel spaghettiPriceLbl;
    private javax.swing.JCheckBox spaghettiSpicy;
    private javax.swing.JLabel subTotalLbl;
    private javax.swing.JLabel totalLbl;
    private javax.swing.JSpinner upCountS;
    private javax.swing.JLabel upLbl;
    private javax.swing.JLabel upPriceLbl;
    private javax.swing.JLabel vatLbl;
    // End of variables declaration//GEN-END:variables
}