
package es.ull.esit.app;

/**
 * @file Info.java
 * @brief Ventana "About us" que muestra la historia y la información del
 *        restaurante.
 *
 *        Clase simple que muestra un texto estático con la historia del
 *        proyecto y
 *        un botón para volver a la pantalla anterior.
 *
 * @version 1.0
 */
public class Info extends javax.swing.JFrame {

  /**
   * Creates new form Info
   */
  public Info() {
    initComponents();
  }

  /**
   * @brief This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    /** Main container panel. */
    javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
    /** Button to go back. */
    javax.swing.JButton jButton3 = new javax.swing.JButton();
    /** Scroll pane that contains the 'ourStory' text area. */
    javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
    /** Text area that contains the story/information about the restaurant. */
    javax.swing.JTextArea ourStory = new javax.swing.JTextArea();
    /** Image/logo displayed in the window. */
    javax.swing.JLabel jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Info");
    setResizable(false);

    jPanel1.setBackground(new java.awt.Color(248, 244, 230));

    jButton3.setBackground(new java.awt.Color(255, 255, 255));
    jButton3.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
    jButton3.setText("Go Back");
    jButton3.addActionListener(this::jButton3ActionPerformed);

    ourStory.setEditable(false);
    ourStory.setBackground(new java.awt.Color(248, 244, 230));
    ourStory.setColumns(20);
    ourStory.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
    ourStory.setRows(5);
    ourStory.setText(
        "  Our Story |\n  Collecting flavors from all over the world to give everyone a taste of what they love. \n\n  Black Plate came in with this vision in mind, to be more of a home rather than an establishment.\n\n  2021 marked the beginning of the journey of Black Plate, starting from Al Khobar.\n\n  Because your visit means a lot to us, we would love to hear your suggestions and concerns \n\n  so we can improve!\n");
    ourStory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    jScrollPane1.setViewportView(ourStory);

    jLabel1.setIcon(new javax.swing.ImageIcon(
        getClass().getResource("/javaapplication2/Screen Shot 1443-09-29 at 4.38.37 PM.png"))); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 141,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1004,
                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(489, 489, 489)
                        .addComponent(jLabel1)))
                .addContainerGap(159, Short.MAX_VALUE)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed

    new Cashier().setVisible(true);
  }// GEN-LAST:event_jButton3ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String[] args) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | java.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new Info().setVisible(true));
  }
}
