
package es.ull.esit.app;

/**
 * @file Login.java
 * @brief Graphical interface for user login.
 *
 *        This class provides a simple Swing window that allows a user to enter
 *        a
 *        username, password, and select a user type (admin or cashier).
 *        Depending on
 *        the provided credentials and selected type, the application opens the
 *        corresponding window (AdminLogin or Cashier).
 *
 *        Documentation intended for use with Doxygen.
 *
 * @version 1.0
 */
public class Login extends javax.swing.JFrame {
  /** Login identifier for admin users. */
  private static final String LOGIN_ADMIN = "admin";
  /** Login identifier for cashier users. */
  private static final String LOGIN_CASHIER = "cashier";

  /**
   * @brief Creates new form Login
   * @return void
   */
  public Login() {
    initComponents();
  }

  /**
   * @brief Initializes GUI components. This method is called from within the
   *        constructor to initialize the form
   * @warning Do NOT modify this code. The content of this method is always
   *          regenerated by the Form Editor.
   * @return void
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents

  /**
   * @brief Initializes GUI components
   * @return void
   */
  private void initComponents() {

    /** Font name used in the UI. */
    final String FONT_NAME = "Yu Gothic UI";
    /** Login identifier for admin users. */


    /** Main container panel. */
    javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
    /** Image/logo displayed in the window. */
    javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
    /** Window title label ("User Login"). */
    javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
    /** Input field for the username. */
    usernametxt = new javax.swing.JTextField();
    /** Combo box to select the user type (admin/cashier). */
    usertypecmbo = new javax.swing.JComboBox<>();
    /** Button to perform login ("Log In"). */
    javax.swing.JButton jButton1 = new javax.swing.JButton();
    /** Input field for the password. */
    jPasswordField1 = new javax.swing.JPasswordField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Login");
    setResizable(false);

    jPanel1.setBackground(new java.awt.Color(248, 244, 230));

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/screenshot.png"))); // NOI18N

    jLabel3.setFont(new java.awt.Font(FONT_NAME, 1, 24)); // NOI18N
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel3.setText("User Login ");

    usernametxt.setFont(new java.awt.Font(FONT_NAME, 0, 18)); // NOI18N
    usernametxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    usernametxt.setBorder(javax.swing.BorderFactory.createTitledBorder(
        new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Username",
        javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP,
        new java.awt.Font(FONT_NAME, 0, 18))); // NOI18N

    usertypecmbo.setEditable(true);
    usertypecmbo.setFont(new java.awt.Font(FONT_NAME, 0, 18)); // NOI18N
    usertypecmbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { LOGIN_ADMIN, LOGIN_CASHIER }));
    usertypecmbo.addActionListener(this::usertypecmboActionPerformed);

    jButton1.setFont(new java.awt.Font(FONT_NAME, 1, 18)); // NOI18N
    jButton1.setText("Log In");
    jButton1.addActionListener(this::jButton1ActionPerformed);

    jPasswordField1.setFont(new java.awt.Font("Thonburi", 0, 18)); // NOI18N
    jPasswordField1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jPasswordField1.setBorder(javax.swing.BorderFactory.createTitledBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Password",
        javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP,
        new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 309,
                            javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 311,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 311,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usertypecmbo, javax.swing.GroupLayout.PREFERRED_SIZE, 311,
                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141,
                            javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 59,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 59,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usertypecmbo, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE)));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @brief Action for the "Log In" button.
   *
   *        Verifies whether the entered credentials correspond to an
   *        administrator
   *        (username and password both equal to "admin"). If so, the admin window
   *        is opened. If the selected user type is "cashier", the cashier window
   *        is opened and the username is passed to it.
   *
   * @param evt Action event associated with the button.
   * @return void
   */
  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
    String password = new String(jPasswordField1.getPassword());
    if (usernametxt.getText().equalsIgnoreCase(LOGIN_ADMIN) && password.equalsIgnoreCase(LOGIN_ADMIN)
        && usertypecmbo.getSelectedItem().toString().equalsIgnoreCase(LOGIN_ADMIN)) {

      new AdminLogin().setVisible(true);
    } else if (usertypecmbo.getSelectedItem().toString().equalsIgnoreCase(LOGIN_CASHIER)) {

      new Cashier(usernametxt.getText()).setVisible(true);
    }
  }// GEN-LAST:event_jButton1ActionPerformed

  /**
   * @brief Handler for changes in the user type combo box.
   *
   *        Method generated by the form editor. It currently does not perform any
   *        action, but remains an extension point if behavior should change when
   *        the user selects a different type.
   *
   * @param evt Action event generated by the combo box.
   * @return void
   */
  private void usertypecmboActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_usertypecmboActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_usertypecmboActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String[] args) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  /** @brief Input field for the password. */
  private javax.swing.JPasswordField jPasswordField1;
  /** @brief Input field for the username. */
  private javax.swing.JTextField usernametxt;
  /** @brief Combo box to select the user type (admin/cashier). */
  private javax.swing.JComboBox<String> usertypecmbo;
  // End of variables declaration//GEN-END:variables
}
