package es.ull.esit.app;

import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 * @file OrderMenu.java
 * @brief Main menu window and receipt management (order UI).
 *
 *        Contains controls to select item quantities (drinks, appetizers,
 *        and main courses), compute subtotals, VAT and total, and provides
 *        basic functionality to save and create receipts.
 */
public class OrderMenu extends javax.swing.JFrame {

  /** Font names used in the UI. */
  static final String FONT_NAME = "Yu Gothic UI";
  static final String FONT_NAME_LIGHT = "Yu Gothic UI Light";
  /** Currency symbol used in the UI. */
  static final String CURRENCY = "0.0 SR";

  /** Counters for selected quantity per product. */
  int colaNum;
  int upNum;
  int orangeNum;
  int mojitoNum;
  int friesNum;
  int moltenNum;
  int macNum;
  int shrimpNum;
  int pizzaNum;
  int pastaNum;
  int salmonNum;
  int spaghettiNum;

  /** Calculated prices per product (quantity * unit cost). */
  double colaPrice;
  double upPrice;
  double mojitoPrice;
  double orangePrice;
  double moltenPrice;
  double macPrice;
  double friesPrice;
  double shrimpPrice;
  double pizzaPrice;
  double pastaPrice;
  double salmonPrice;
  double spaghettiPrice;

  /** Unit cost constants per product. */
  static final double COLA_COST = 6.0;
  static final double UP_COST = 6.0;
  static final double MOJITO_COST = 14.0;
  static final double ORANGE_COST = 10.0;
  static final double MOLTEN_COST = 28.0;
  static final double MAC_COST = 39.0;
  static final double FRIES_COST = 32.0;
  static final double SHRIMP_COST = 42.0;
  static final double PIZZA_COST = 60.0;
  static final double PASTA_COST = 52.0;
  static final double SALMON_COST = 71.0;
  static final double SPAGHETTI_COST = 55.0;

  /** Totals and derived values. */
  double subTotal;
  double vat;
  double total;

  /** Current receipt number (used when saving). */
  int receiptNo;
  /** Writer to save receipts to disk. */
  transient PrintWriter output;

  /**
   * Creates new form OrderMenu
   */
  public OrderMenu() {
    initComponents();
  }

  /**
   * Loads prices for all products based on current quantities.
   */
  void loadPrice() {
    // (No se usa por ahora – lo dejamos preparado por si lo necesitas)
  }

  /**
   * @brief This method is called from within the constructor to initialize the
   *        form.
   *        WARNING: Do NOT modify this code. The content of this method is always
   *        regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    final javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
    DrinksPnl = new javax.swing.JPanel();
    javax.swing.JLabel colaLbl = new javax.swing.JLabel();
    final javax.swing.JLabel upLbl = new javax.swing.JLabel();
    javax.swing.JLabel mojitoLbl = new javax.swing.JLabel();
    colaCountS = new javax.swing.JSpinner();
    upCountS = new javax.swing.JSpinner();
    mojitoCountS = new javax.swing.JSpinner();
    javax.swing.JLabel orangLbl = new javax.swing.JLabel();
    orangeCountS = new javax.swing.JSpinner();
    orangePriceLbl = new javax.swing.JLabel();
    upPriceLbl = new javax.swing.JLabel();
    colaPriceLbl = new javax.swing.JLabel();
    mojitoPriceLbl = new javax.swing.JLabel();
    AppetizerPnl = new javax.swing.JPanel();
    javax.swing.JLabel friesLbl = new javax.swing.JLabel();
    javax.swing.JLabel moltenLbl = new javax.swing.JLabel();
    javax.swing.JLabel shrimpLbl = new javax.swing.JLabel();
    friesCountS = new javax.swing.JSpinner();
    moltenCountS = new javax.swing.JSpinner();
    shrimpCountS = new javax.swing.JSpinner();
    javax.swing.JLabel macLbl = new javax.swing.JLabel();
    macCountS = new javax.swing.JSpinner();
    friesPriceLbl = new javax.swing.JLabel();
    moltenPriceLbl = new javax.swing.JLabel();
    macPriceLbl = new javax.swing.JLabel();
    shrimpPriceLbl = new javax.swing.JLabel();
    MainCoursePnl = new javax.swing.JPanel();
    final javax.swing.JLabel pizzaLbl = new javax.swing.JLabel();
    final javax.swing.JLabel pastaLbl = new javax.swing.JLabel();
    final javax.swing.JLabel spaghettiLbl = new javax.swing.JLabel();
    pizzaCountS = new javax.swing.JSpinner();
    pastaCountS = new javax.swing.JSpinner();
    spaghettiCountS = new javax.swing.JSpinner();
    final javax.swing.JLabel salmonLbl = new javax.swing.JLabel();
    salmonCountS = new javax.swing.JSpinner();
    pizzaPriceLbl = new javax.swing.JLabel();
    spaghettiPriceLbl = new javax.swing.JLabel();
    salmonPriceLbl = new javax.swing.JLabel();
    pastaPriceLbl = new javax.swing.JLabel();
    spaghettiSpicy = new javax.swing.JCheckBox();
    pizzaSpicy = new javax.swing.JCheckBox();
    pastaChicken = new javax.swing.JCheckBox();
    salmonRice = new javax.swing.JCheckBox();
    final javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
    subTotalLbl = new javax.swing.JLabel();
    vatLbl = new javax.swing.JLabel();
    totalLbl = new javax.swing.JLabel();
    receiptNoLbl = new javax.swing.JLabel();
    final javax.swing.JButton payBtn = new javax.swing.JButton();
    final javax.swing.JButton newReceiptBtn = new javax.swing.JButton();
    final javax.swing.JButton saveReceiptBtn = new javax.swing.JButton();
    javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
    javax.swing.JButton goBackMenueBtn = new javax.swing.JButton();
    javax.swing.JLabel jLabel2 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Menu");
    setBackground(new java.awt.Color(204, 204, 204));
    setResizable(false);

    jPanel2.setBackground(new java.awt.Color(248, 244, 230));

    DrinksPnl.setBackground(new java.awt.Color(248, 244, 230));
    DrinksPnl.setBorder(javax.swing.BorderFactory.createTitledBorder(
        new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Drinks",
        javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP,
        new java.awt.Font(FONT_NAME, 0, 18))); // NOI18N
    DrinksPnl.setPreferredSize(new java.awt.Dimension(260, 278));

    colaLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    colaLbl.setText("Cola");

    upLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    upLbl.setText("7up");

    mojitoLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    mojitoLbl.setText("Mojito");

    colaCountS.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    colaCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
    colaCountS.addChangeListener(this::colaCountSStateChanged);

    upCountS.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    upCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
    upCountS.addChangeListener(this::upCountSStateChanged);

    mojitoCountS.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    mojitoCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
    mojitoCountS.addChangeListener(this::mojitoCountSStateChanged);

    orangLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    orangLbl.setText("Orange juice");

    orangeCountS.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    orangeCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
    orangeCountS.addChangeListener(this::orangeCountSStateChanged);

    orangePriceLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    orangePriceLbl.setText(CURRENCY);

    upPriceLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    upPriceLbl.setText(CURRENCY);

    colaPriceLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    colaPriceLbl.setText(CURRENCY);

    mojitoPriceLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    mojitoPriceLbl.setText(CURRENCY);

    javax.swing.GroupLayout drinksPnlLayout = new javax.swing.GroupLayout(DrinksPnl);
    DrinksPnl.setLayout(drinksPnlLayout);
    drinksPnlLayout.setHorizontalGroup(
        drinksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drinksPnlLayout.createSequentialGroup()
                .addGroup(drinksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(drinksPnlLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(colaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(colaCountS, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(colaPriceLbl))
                    .addGroup(drinksPnlLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(upLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(upCountS, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(upPriceLbl))
                    .addGroup(drinksPnlLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(orangLbl)
                        .addGap(12, 12, 12)
                        .addComponent(orangeCountS, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(orangePriceLbl))
                    .addGroup(drinksPnlLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(mojitoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(mojitoCountS, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mojitoPriceLbl)))
                .addContainerGap(14, Short.MAX_VALUE)));
    drinksPnlLayout.setVerticalGroup(
        drinksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drinksPnlLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(drinksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colaLbl)
                    .addGroup(drinksPnlLayout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(colaPriceLbl)
                        .addComponent(colaCountS, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(drinksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upLbl)
                    .addGroup(drinksPnlLayout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(upPriceLbl)
                        .addComponent(upCountS, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(drinksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orangLbl)
                    .addGroup(drinksPnlLayout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(orangeCountS, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(orangePriceLbl)))
                .addGroup(drinksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(drinksPnlLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(mojitoLbl))
                    .addGroup(drinksPnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(drinksPnlLayout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mojitoCountS,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mojitoPriceLbl))))
                .addContainerGap(28, Short.MAX_VALUE)));

    AppetizerPnl.setBackground(new java.awt.Color(248, 244, 230));
    AppetizerPnl.setBorder(javax.swing.BorderFactory.createTitledBorder(
        new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Appetizers",
        javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP,
        new java.awt.Font(FONT_NAME, 0, 18))); // NOI18N
    AppetizerPnl.setPreferredSize(new java.awt.Dimension(260, 278));

    friesLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    friesLbl.setText("Truffel Fries");

    moltenLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    moltenLbl.setText("Molten Chocolate");

    shrimpLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    shrimpLbl.setText("Dynamite Shrimp");

    friesCountS.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    friesCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
    friesCountS.addChangeListener(this::friesCountSStateChanged);

    moltenCountS.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    moltenCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
    moltenCountS.addChangeListener(this::moltenCountSStateChanged);

    shrimpCountS.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    shrimpCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
    shrimpCountS.addChangeListener(this::shrimpCountSStateChanged);

    macLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    macLbl.setText("Mac&Cheese Balls");

    macCountS.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    macCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
    macCountS.addChangeListener(this::macCountSStateChanged);

    friesPriceLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    friesPriceLbl.setText(CURRENCY);

    moltenPriceLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    moltenPriceLbl.setText(CURRENCY);

    macPriceLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    macPriceLbl.setText(CURRENCY);

    shrimpPriceLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    shrimpPriceLbl.setText(CURRENCY);

    javax.swing.GroupLayout appetizerPnlLayout = new javax.swing.GroupLayout(AppetizerPnl);
    AppetizerPnl.setLayout(appetizerPnlLayout);
    appetizerPnlLayout.setHorizontalGroup(
        appetizerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appetizerPnlLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(appetizerPnlLayout
                    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(appetizerPnlLayout.createSequentialGroup()
                        .addComponent(friesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31,
                            Short.MAX_VALUE)
                        .addComponent(friesCountS, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(friesPriceLbl))
                    .addGroup(appetizerPnlLayout.createSequentialGroup()
                        .addComponent(shrimpLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(shrimpCountS, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(shrimpPriceLbl))
                    .addGroup(appetizerPnlLayout.createSequentialGroup()
                        .addComponent(moltenLbl, javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(moltenCountS, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(moltenPriceLbl))
                    .addGroup(appetizerPnlLayout.createSequentialGroup()
                        .addComponent(macLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(macCountS, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(macPriceLbl)))
                .addContainerGap()));
    appetizerPnlLayout.setVerticalGroup(
        appetizerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, appetizerPnlLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(appetizerPnlLayout
                    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(friesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(appetizerPnlLayout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(friesCountS, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(friesPriceLbl)))
                .addGap(10, 10, 10)
                .addGroup(appetizerPnlLayout
                    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moltenLbl)
                    .addGroup(appetizerPnlLayout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(moltenCountS, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(moltenPriceLbl)))
                .addGroup(appetizerPnlLayout
                    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(appetizerPnlLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(macLbl))
                    .addGroup(appetizerPnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(appetizerPnlLayout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(macPriceLbl)
                            .addComponent(macCountS, javax.swing.GroupLayout.PREFERRED_SIZE,
                                30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16)
                .addGroup(appetizerPnlLayout
                    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shrimpLbl)
                    .addGroup(appetizerPnlLayout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(shrimpCountS, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(shrimpPriceLbl)))
                .addContainerGap()));

    MainCoursePnl.setBackground(new java.awt.Color(248, 244, 230));
    MainCoursePnl.setBorder(javax.swing.BorderFactory.createTitledBorder(
        new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Main Course",
        javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP,
        new java.awt.Font(FONT_NAME, 0, 18))); // NOI18N
    MainCoursePnl.setPreferredSize(new java.awt.Dimension(260, 278));

    pizzaLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    pizzaLbl.setText("Buratta Pizza");

    pastaLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    pastaLbl.setText("Pink Pasta");
    pastaLbl.setToolTipText("");

    spaghettiLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    spaghettiLbl.setText("Spaghetti");

    pizzaCountS.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    pizzaCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
    pizzaCountS.addChangeListener(this::pizzaCountSStateChanged);

    pastaCountS.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    pastaCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
    pastaCountS.addChangeListener(this::pastaCountSStateChanged);

    spaghettiCountS.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    spaghettiCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
    spaghettiCountS.addChangeListener(this::spaghettiCountSStateChanged);

    salmonLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    salmonLbl.setText("Rosemary Salmon");

    salmonCountS.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    salmonCountS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
    salmonCountS.addChangeListener(this::salmonCountSStateChanged);

    pizzaPriceLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    pizzaPriceLbl.setText(CURRENCY);

    spaghettiPriceLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    spaghettiPriceLbl.setText(CURRENCY);

    salmonPriceLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    salmonPriceLbl.setText(CURRENCY);

    pastaPriceLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    pastaPriceLbl.setText(CURRENCY);

    spaghettiSpicy.setBackground(new java.awt.Color(255, 255, 255));
    spaghettiSpicy.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    spaghettiSpicy.setText("Spicy");
    spaghettiSpicy.addActionListener(this::spaghettiSpicyActionPerformed);

    pizzaSpicy.setBackground(new java.awt.Color(255, 255, 255));
    pizzaSpicy.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    pizzaSpicy.setText("Spicy");
    pizzaSpicy.addActionListener(this::pizzaSpicyActionPerformed);

    pastaChicken.setBackground(new java.awt.Color(255, 255, 255));
    pastaChicken.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    pastaChicken.setText("Chicken");
    pastaChicken.addActionListener(this::pastaChickenActionPerformed);

    salmonRice.setBackground(new java.awt.Color(255, 255, 255));
    salmonRice.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    salmonRice.setText("Rice");
    salmonRice.addActionListener(this::salmonRiceActionPerformed);

    javax.swing.GroupLayout mainCoursePnlLayout = new javax.swing.GroupLayout(MainCoursePnl);
    MainCoursePnl.setLayout(mainCoursePnlLayout);
    mainCoursePnlLayout.setHorizontalGroup(
        mainCoursePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainCoursePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainCoursePnlLayout
                    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pizzaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 121,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainCoursePnlLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(mainCoursePnlLayout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                false)
                            .addComponent(spaghettiLbl,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pastaLbl,
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salmonLbl,
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 163,
                                Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainCoursePnlLayout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                mainCoursePnlLayout.createSequentialGroup()
                                    .addComponent(pizzaCountS,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(mainCoursePnlLayout
                                        .createParallelGroup(
                                            javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(mainCoursePnlLayout
                                            .createSequentialGroup()
                                            .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(pizzaSpicy)
                                            .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                                        .addGroup(
                                            javax.swing.GroupLayout.Alignment.TRAILING,
                                            mainCoursePnlLayout
                                                .createSequentialGroup()
                                                .addPreferredGap(
                                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE)
                                                .addGroup(
                                                    mainCoursePnlLayout
                                                        .createParallelGroup(
                                                            javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(
                                                            salmonRice)
                                                        .addComponent(
                                                            pastaChicken)
                                                        .addComponent(
                                                            spaghettiSpicy))
                                                .addGap(18, 18, 18)))
                                    .addComponent(pizzaPriceLbl))
                            .addGroup(mainCoursePnlLayout.createSequentialGroup()
                                .addGroup(mainCoursePnlLayout.createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(spaghettiCountS,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        74,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(salmonCountS,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        74,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pastaCountS,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    Short.MAX_VALUE)
                                .addGroup(mainCoursePnlLayout.createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pastaPriceLbl,
                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(salmonPriceLbl,
                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(spaghettiPriceLbl,
                                        javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(21, Short.MAX_VALUE)));
    mainCoursePnlLayout.setVerticalGroup(
        mainCoursePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainCoursePnlLayout
                .createSequentialGroup()
                .addGroup(mainCoursePnlLayout
                    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainCoursePnlLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(pizzaPriceLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pastaPriceLbl)
                        .addGap(13, 13, 13))
                    .addGroup(mainCoursePnlLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainCoursePnlLayout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainCoursePnlLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(pizzaLbl))
                            .addGroup(mainCoursePnlLayout
                                .createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pizzaSpicy)
                                .addComponent(pizzaCountS,
                                    javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(mainCoursePnlLayout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainCoursePnlLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(mainCoursePnlLayout.createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pastaLbl)
                                    .addComponent(pastaCountS,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(mainCoursePnlLayout.createSequentialGroup()
                                .addPreferredGap(
                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pastaChicken)))
                        .addGap(1, 1, 1)))
                .addGroup(mainCoursePnlLayout
                    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salmonLbl)
                    .addComponent(salmonCountS, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salmonPriceLbl)
                    .addComponent(salmonRice))
                .addGroup(mainCoursePnlLayout
                    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainCoursePnlLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(mainCoursePnlLayout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spaghettiLbl)
                            .addGroup(mainCoursePnlLayout
                                .createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(spaghettiSpicy)
                                .addComponent(spaghettiCountS,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(mainCoursePnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spaghettiPriceLbl)))
                .addGap(8, 8, 8)));

    jPanel1.setBackground(new java.awt.Color(248, 244, 230));
    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(
        new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Receipt",
        javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP,
        new java.awt.Font(FONT_NAME, 0, 14))); // NOI18N

    subTotalLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    subTotalLbl.setText("SubTotal: 0.0 SR");

    vatLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    vatLbl.setText("VAT included: 0.0 SR");

    totalLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 18)); // NOI18N
    totalLbl.setText("Total: 0.0 SR");

    receiptNoLbl.setFont(new java.awt.Font(FONT_NAME_LIGHT, 0, 14)); // NOI18N
    receiptNoLbl.setText("Receipt No. : 0");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalLbl)
                            .addComponent(subTotalLbl))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(vatLbl)
                        .addGap(0, 108, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(receiptNoLbl)
                .addGap(0, 0, Short.MAX_VALUE)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subTotalLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vatLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10,
                    Short.MAX_VALUE)
                .addComponent(receiptNoLbl)));

    payBtn.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
    payBtn.setText("Pay");
    payBtn.addActionListener(this::payBtnActionPerformed);

    newReceiptBtn.setFont(new java.awt.Font(FONT_NAME, 1, 14)); // NOI18N
    newReceiptBtn.setText("New Receipt");
    newReceiptBtn.addActionListener(this::newReceiptBtnActionPerformed);

    saveReceiptBtn.setFont(new java.awt.Font(FONT_NAME, 1, 14)); // NOI18N
    saveReceiptBtn.setText("Save Receipt");
    saveReceiptBtn.addActionListener(this::saveReceiptBtnActionPerformed);

    jLabel1.setBackground(new java.awt.Color(255, 153, 0));
    jLabel1.setFont(new java.awt.Font(FONT_NAME, 1, 36)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("BLACK PLATE MENU");

    goBackMenueBtn.setFont(new java.awt.Font(FONT_NAME, 1, 14)); // NOI18N
    goBackMenueBtn.setText("Go Back");
    goBackMenueBtn.addActionListener(this::goBackMenueBtnActionPerformed);

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/screenshot.png"))); // NOI18N

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(goBackMenueBtn,
                                    javax.swing.GroupLayout.PREFERRED_SIZE, 130,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                    147, Short.MAX_VALUE)
                                .addComponent(payBtn,
                                    javax.swing.GroupLayout.PREFERRED_SIZE, 180,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                    javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saveReceiptBtn,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        220,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newReceiptBtn,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        220,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(jPanel1,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                jPanel2Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(AppetizerPnl,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        382,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(MainCoursePnl,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        453,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(DrinksPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 293,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(59, 59, 59)))
                .addGroup(jPanel2Layout
                    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AppetizerPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 210,
                        Short.MAX_VALUE)
                    .addComponent(MainCoursePnl, javax.swing.GroupLayout.DEFAULT_SIZE, 210,
                        Short.MAX_VALUE)
                    .addComponent(DrinksPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 210,
                        Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                        .createSequentialGroup()
                        .addComponent(goBackMenueBtn, javax.swing.GroupLayout.PREFERRED_SIZE,
                            40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        jPanel2Layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                        .createSequentialGroup()
                        .addGroup(jPanel2Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(payBtn, javax.swing.GroupLayout.PREFERRED_SIZE,
                                70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(newReceiptBtn,
                                    javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                    javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saveReceiptBtn,
                                    javax.swing.GroupLayout.PREFERRED_SIZE, 29,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)))));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap()));

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  /**
   * Called when the state of the colaCountS spinner changes.
   *
   * @param evt the change event
   */
  private void colaCountSStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_colaCountSStateChanged
    colaNum = (Integer) colaCountS.getValue();
    colaPrice = COLA_COST * colaNum;
    colaPriceLbl.setText(colaPrice + " SR");
  }// GEN-LAST:event_colaCountSStateChanged

  /**
   * Called when the state of the upCountS spinner changes.
   *
   * @param evt the change event
   */
  private void upCountSStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_upCountSStateChanged
    upNum = (Integer) upCountS.getValue();
    upPrice = UP_COST * upNum;
    upPriceLbl.setText(upPrice + " SR");
  }// GEN-LAST:event_upCountSStateChanged

  /**
   * Called when the state of the mojitoCountS spinner changes.
   *
   * @param evt the change event
   */
  private void mojitoCountSStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_mojitoCountSStateChanged
    mojitoNum = (Integer) mojitoCountS.getValue();
    mojitoPrice = MOJITO_COST * mojitoNum;
    mojitoPriceLbl.setText(mojitoPrice + " SR");
  }// GEN-LAST:event_mojitoCountSStateChanged

  /**
   * Called when the state of the orangeCountS spinner changes.
   *
   * @param evt the change event
   */
  private void orangeCountSStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_orangeCountSStateChanged
    orangeNum = (Integer) orangeCountS.getValue();
    orangePrice = ORANGE_COST * orangeNum;
    orangePriceLbl.setText(orangePrice + " SR");
  }// GEN-LAST:event_orangeCountSStateChanged

  /**
   * Called when the state of the friesCountS spinner changes.
   *
   * @param evt the change event
   */
  private void friesCountSStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_friesCountSStateChanged
    friesNum = (Integer) friesCountS.getValue();
    friesPrice = FRIES_COST * friesNum;
    friesPriceLbl.setText(friesPrice + " SR");
  }// GEN-LAST:event_friesCountSStateChanged

  /**
   * Called when the state of the moltenCountS spinner changes.
   *
   * @param evt the change event
   */
  private void moltenCountSStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_moltenCountSStateChanged
    moltenNum = (Integer) moltenCountS.getValue();
    moltenPrice = MOLTEN_COST * moltenNum;
    moltenPriceLbl.setText(moltenPrice + " SR");
  }// GEN-LAST:event_moltenCountSStateChanged

  /**
   * Called when the state of the shrimpCountS spinner changes.
   *
   * @param evt the change event
   */
  private void shrimpCountSStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_shrimpCountSStateChanged
    shrimpNum = (Integer) shrimpCountS.getValue();
    shrimpPrice = SHRIMP_COST * shrimpNum;
    shrimpPriceLbl.setText(shrimpPrice + " SR");
  }// GEN-LAST:event_shrimpCountSStateChanged

  /**
   * Called when the state of the macCountS spinner changes.
   *
   * @param evt the change event
   */
  private void macCountSStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_macCountSStateChanged
    macNum = (Integer) macCountS.getValue();
    macPrice = MAC_COST * macNum;
    macPriceLbl.setText(macPrice + " SR");
  }// GEN-LAST:event_macCountSStateChanged

  /**
   * Called when the state of the pizzaCountS spinner changes.
   *
   * @param evt the change event
   */
  private void pizzaCountSStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_pizzaCountSStateChanged
    pizzaNum = (Integer) pizzaCountS.getValue();
    pizzaPrice = PIZZA_COST * pizzaNum;
    pizzaPriceLbl.setText(pizzaPrice + " SR");
  }// GEN-LAST:event_pizzaCountSStateChanged

  /**
   * Called when the state of the pastaCountS spinner changes.
   *
   * @param evt the change event
   */
  private void pastaCountSStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_pastaCountSStateChanged
    pastaNum = (Integer) pastaCountS.getValue();
    pastaPrice = PASTA_COST * pastaNum;
    pastaPriceLbl.setText(pastaPrice + " SR");
  }// GEN-LAST:event_pastaCountSStateChanged

  /**
   * Called when the state of the spaghettiCountS spinner changes.
   *
   * @param evt the change event
   */
  private void spaghettiCountSStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_spaghettiCountSStateChanged
    spaghettiNum = (Integer) spaghettiCountS.getValue();
    spaghettiPrice = SPAGHETTI_COST * spaghettiNum;
    spaghettiPriceLbl.setText(spaghettiPrice + " SR");
  }// GEN-LAST:event_spaghettiCountSStateChanged

  /**
   * Called when the state of the salmonCountS spinner changes.
   *
   * @param evt the change event
   */
  private void salmonCountSStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_salmonCountSStateChanged
    salmonNum = (Integer) salmonCountS.getValue();
    salmonPrice = SALMON_COST * salmonNum;
    salmonPriceLbl.setText(salmonPrice + " SR");
  }// GEN-LAST:event_salmonCountSStateChanged

  /**
   * Called when the spaghettiSpicy checkbox is toggled.
   *
   * @param evt the action event
   */
  private void spaghettiSpicyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_spaghettiSpicyActionPerformed
    if (spaghettiSpicy.isSelected()) {
      spaghettiPrice += spaghettiNum;
    } else {
      spaghettiPrice -= spaghettiNum;
    }
    spaghettiPriceLbl.setText(spaghettiPrice + " SR");
  }// GEN-LAST:event_spaghettiSpicyActionPerformed

  /**
   * Called when the pizzaSpicy checkbox is toggled.
   *
   * @param evt the action event
   */
  private void pizzaSpicyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pizzaSpicyActionPerformed
    if (pizzaSpicy.isSelected()) {
      pizzaPrice += pizzaNum;
    } else {
      pizzaPrice -= pizzaNum;
    }
    pizzaPriceLbl.setText(pizzaPrice + " SR");
  }// GEN-LAST:event_pizzaSpicyActionPerformed

  /**
   * Called when the pastaChicken checkbox is toggled.
   *
   * @param evt the action event
   */
  private void pastaChickenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pastaChickenActionPerformed
    if (pastaChicken.isSelected()) {
      pastaPrice += pastaNum;
    } else {
      pastaPrice -= pastaNum;
    }
    pastaPriceLbl.setText(pastaPrice + " SR");
  }// GEN-LAST:event_pastaChickenActionPerformed

  /**
   * Called when the salmonRice checkbox is toggled.
   *
   * @param evt the action event
   */
  private void salmonRiceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_salmonRiceActionPerformed
    if (salmonRice.isSelected()) {
      salmonPrice += salmonNum;
    } else {
      salmonPrice -= salmonNum;
    }
    salmonPriceLbl.setText(salmonPrice + " SR");
  }// GEN-LAST:event_salmonRiceActionPerformed

  /**
   * Called when the payBtn button is clicked.
   *
   * @param evt the action event
   */
  private void payBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_payBtnActionPerformed

    subTotal = colaPrice + upPrice + mojitoPrice + orangePrice
        + friesPrice + moltenPrice + macPrice + shrimpPrice
        + pizzaPrice + pastaPrice + salmonPrice + spaghettiPrice;

    subTotalLbl.setText("SubTotal: " + subTotal + " SR");

    vat = subTotal * 0.15;
    vatLbl.setText("VAT included: " + vat + " SR");

    total = subTotal + vat;
    totalLbl.setText("Total: " + total + " SR");

    if (subTotal == 0) {
      JOptionPane.showMessageDialog(null,
          "Please select an item first!", null,
          JOptionPane.INFORMATION_MESSAGE);
    } else {
      JOptionPane.showMessageDialog(null, "Paid successfully");
    }
  }// GEN-LAST:event_payBtnActionPerformed

  /**
   * Called when the saveReceiptBtn button is clicked.
   *
   * @param evt the action event
   */
  private void saveReceiptBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_saveReceiptBtnActionPerformed

    try {
      if (total != 0) {

        output = new PrintWriter("receipts/billNo." + receiptNo + ".txt");

        JOptionPane.showMessageDialog(null,
            "Recipt number: " + receiptNo + "  has been saved successfuly");

        output.println(" Bill number is: " + receiptNo);
        output.println("==============");
        output.println("--------------");
        output.println("Subtotal is: " + subTotal + " SR");
        output.println("vat: " + vat + " SR");
        output.println("Total is: " + total + " SR");
        output.println();
        output.println("THANK YOU FOR ORDERING");

        output.close();
      }

    } catch (Exception ex) {
      JOptionPane.showMessageDialog(null, "Error occured. Please try again");

    }
  }// GEN-LAST:event_saveReceiptBtnActionPerformed

  /**
   * Called when the newReceiptBtn button is clicked.
   *
   * @param evt the action event
   */
  private void newReceiptBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_newReceiptBtnActionPerformed
    if (total != 0) {

      colaCountS.setValue(0);
      upCountS.setValue(0);
      orangeCountS.setValue(0);
      mojitoCountS.setValue(0);

      friesCountS.setValue(0);
      moltenCountS.setValue(0);
      macCountS.setValue(0);
      shrimpCountS.setValue(0);

      pizzaCountS.setValue(0);
      pastaCountS.setValue(0);
      salmonCountS.setValue(0);
      spaghettiCountS.setValue(0);

      pizzaSpicy.setSelected(false);
      pastaChicken.setSelected(false);
      salmonRice.setSelected(false);
      spaghettiSpicy.setSelected(false);

      subTotalLbl.setText("SubTotal : 0.0 SR");
      vatLbl.setText("VAT included : 0.0 SR");
      totalLbl.setText("Total : 0.0 SR");

      subTotal = 0;
      vat = 0;
      total = 0;

      receiptNo++;
      receiptNoLbl.setText("ReceiptNo. :" + receiptNo);
    }
  }// GEN-LAST:event_newReceiptBtnActionPerformed

  /**
   * Called when the goBackMenueBtn button is clicked.
   *
   * @param evt the action event
   */
  private void goBackMenueBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_goBackMenueBtnActionPerformed
    this.dispose();
    new Login().setVisible(true);
  }// GEN-LAST:event_goBackMenueBtnActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String[] args) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
        | javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(OrderMenu.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new OrderMenu().setVisible(true));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel DrinksPnl;
  private javax.swing.JPanel AppetizerPnl;
  private javax.swing.JPanel MainCoursePnl;

  /** Spinner for Cola quantity. */
  private javax.swing.JSpinner colaCountS;
  /** Calculated price for Cola. */
  private javax.swing.JLabel colaPriceLbl;

  private javax.swing.JSpinner friesCountS;
  private javax.swing.JLabel friesPriceLbl;

  private javax.swing.JSpinner macCountS;
  private javax.swing.JLabel macPriceLbl;

  private javax.swing.JSpinner mojitoCountS;
  private javax.swing.JLabel mojitoPriceLbl;

  private javax.swing.JSpinner moltenCountS;
  private javax.swing.JLabel moltenPriceLbl;

  private javax.swing.JSpinner orangeCountS;
  private javax.swing.JLabel orangePriceLbl;

  private javax.swing.JCheckBox pastaChicken;
  private javax.swing.JSpinner pastaCountS;
  private javax.swing.JLabel pastaPriceLbl;

  private javax.swing.JSpinner pizzaCountS;
  private javax.swing.JLabel pizzaPriceLbl;
  private javax.swing.JCheckBox pizzaSpicy;

  private javax.swing.JLabel receiptNoLbl;

  private javax.swing.JSpinner salmonCountS;
  private javax.swing.JLabel salmonPriceLbl;
  private javax.swing.JCheckBox salmonRice;

  private javax.swing.JSpinner shrimpCountS;
  private javax.swing.JLabel shrimpPriceLbl;

  private javax.swing.JSpinner spaghettiCountS;
  private javax.swing.JLabel spaghettiPriceLbl;
  private javax.swing.JCheckBox spaghettiSpicy;

  private javax.swing.JLabel subTotalLbl;
  private javax.swing.JLabel totalLbl;

  private javax.swing.JSpinner upCountS;
  private javax.swing.JLabel upPriceLbl;

  private javax.swing.JLabel vatLbl;
  // End of variables declaration//GEN-END:variables

}
