var searchData=
[
  ['la_20base_20de_20datos_0',['🔍 Verificación de la Base de Datos',['../md_POSTMAN-EXAMPLES.html#autotoc_md47',1,'']]],
  ['la_20base_20de_20datos_1',['la base de datos',['../md_TEST-INSTRUCTIONS.html#autotoc_md95',1,'Cashiers válidos en la base de datos'],['../md_DOCKER-INSTRUCTIONS.html#autotoc_md11',1,'Credenciales de la base de datos']]],
  ['la_20base_20de_20datos_20mysql_2',['Paso 1: Levantar la base de datos MySQL',['../md_TEST-INSTRUCTIONS.html#autotoc_md82',1,'']]],
  ['la_20base_20de_20datos_20mysql_20con_20docker_3',['Instrucciones para levantar la base de datos MySQL con Docker',['../md_DOCKER-INSTRUCTIONS.html',1,'']]],
  ['la_20base_20de_20datos_20project3_20fue_20creada_4',['5. Verificar que la base de datos &lt;span class=&quot;tt&quot;&gt;project3&lt;/span&gt; fue creada',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md6',1,'']]],
  ['la_20bbdd_20mysql_20mariadb_5',['Configuración de la BBDD (MySQL / MariaDB)',['../md_README.html#autotoc_md79',1,'']]],
  ['la_20bd_6',['🎯 Cajeros Válidos en la BD',['../md_QUICK-START.html#autotoc_md69',1,'']]],
  ['la_20bd_3a_7',['Cashiers válidos en la BD:',['../md_POSTMAN-EXAMPLES.html#autotoc_md44',1,'']]],
  ['lanzado_20guía_20rápida_20de_20testing_8',['🚀 SERVIDOR LANZADO - Guía Rápida de Testing',['../md_QUICK-START.html',1,'']]],
  ['las_20peticiones_3a_9',['Cómo crear las peticiones:',['../md_POSTMAN-EXAMPLES.html#autotoc_md43',1,'']]],
  ['las_20tablas_20creadas_10',['6. Verificar las tablas creadas',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md7',1,'']]],
  ['levantar_20el_20contenedor_20mysql_20con_20docker_20compose_11',['2. Levantar el contenedor MySQL con Docker Compose',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md3',1,'']]],
  ['levantar_20la_20base_20de_20datos_20mysql_12',['Paso 1: Levantar la base de datos MySQL',['../md_TEST-INSTRUCTIONS.html#autotoc_md82',1,'']]],
  ['levantar_20la_20base_20de_20datos_20mysql_20con_20docker_13',['Instrucciones para levantar la base de datos MySQL con Docker',['../md_DOCKER-INSTRUCTIONS.html',1,'']]],
  ['listo_14',['🎉 ¡Todo Listo!',['../md_QUICK-START.html#autotoc_md78',1,'']]],
  ['login_20éxito_15',['✅ POST /api/login (Éxito)',['../md_QUICK-START.html#autotoc_md65',1,'']]],
  ['login_20cashier_20existente_16',['POST /api/login (cashier existente)',['../md_TEST-INSTRUCTIONS.html#autotoc_md93',1,'']]],
  ['login_20cashier_20no_20existente_17',['POST /api/login (cashier no existente)',['../md_TEST-INSTRUCTIONS.html#autotoc_md94',1,'']]],
  ['login_20con_20otro_20cajero_18',['4️⃣ POST - Login con Otro Cajero',['../md_QUICK-START.html#autotoc_md58',1,'']]],
  ['login_20de_20cajero_20éxito_19',['3️⃣ POST - Login de Cajero (Éxito)',['../md_POSTMAN-EXAMPLES.html#autotoc_md26',1,'']]],
  ['login_20de_20cajero_20cajero_20no_20existente_20',['4️⃣ POST - Login de Cajero (Cajero No Existente)',['../md_POSTMAN-EXAMPLES.html#autotoc_md30',1,'']]],
  ['login_20de_20cajero_20otro_20cajero_20válido_21',['5️⃣ POST - Login de Cajero (Otro cajero válido)',['../md_POSTMAN-EXAMPLES.html#autotoc_md34',1,'']]],
  ['login_20error_20usuario_20no_20existe_22',['❌ POST /api/login (Error - Usuario No Existe)',['../md_QUICK-START.html#autotoc_md66',1,'']]],
  ['login_20error_20validación_23',['❌ POST /api/login (Error - Validación)',['../md_QUICK-START.html#autotoc_md67',1,'']]],
  ['login_20exitoso_24',['3️⃣ POST - Login Exitoso',['../md_QUICK-START.html#autotoc_md57',1,'']]],
  ['login_20fallido_20usuario_20no_20existe_25',['5️⃣ POST - Login Fallido (Usuario No Existe)',['../md_QUICK-START.html#autotoc_md59',1,'']]],
  ['login_20sin_20nombre_20error_20de_20validación_26',['6️⃣ POST - Login sin nombre (Error de validación)',['../md_POSTMAN-EXAMPLES.html#autotoc_md38',1,'']]],
  ['logs_20de_20inicialización_20opcional_27',['4. Ver los logs de inicialización (opcional)',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md5',1,'']]],
  ['los_20endpoints_28',['Paso 3: Testear los endpoints',['../md_TEST-INSTRUCTIONS.html#autotoc_md86',1,'']]],
  ['los_20logs_20de_20inicialización_20opcional_29',['4. Ver los logs de inicialización (opcional)',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md5',1,'']]]
];
