var searchData=
[
  ['para_20ejecutar_3a_0',['Pasos para ejecutar:',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md1',1,'']]],
  ['para_20levantar_20la_20base_20de_20datos_20mysql_20con_20docker_1',['Instrucciones para levantar la base de datos MySQL con Docker',['../md_DOCKER-INSTRUCTIONS.html',1,'']]],
  ['para_20postman_2',['📮 PETICIONES RÁPIDAS PARA POSTMAN',['../md_QUICK-START.html#autotoc_md51',1,'']]],
  ['para_20postman_3',['para Postman',['../md_POSTMAN-EXAMPLES.html#autotoc_md42',1,'📝 Notas para Postman'],['../md_POSTMAN-EXAMPLES.html',1,'📮 Peticiones de Ejemplo para Postman']]],
  ['paso_201_3a_20levantar_20la_20base_20de_20datos_20mysql_4',['Paso 1: Levantar la base de datos MySQL',['../md_TEST-INSTRUCTIONS.html#autotoc_md82',1,'']]],
  ['paso_202_3a_20compilar_20y_20arrancar_20el_20servidor_5',['Paso 2: Compilar y arrancar el servidor',['../md_TEST-INSTRUCTIONS.html#autotoc_md83',1,'']]],
  ['paso_203_3a_20testear_20los_20endpoints_6',['Paso 3: Testear los endpoints',['../md_TEST-INSTRUCTIONS.html#autotoc_md86',1,'']]],
  ['pasos_20para_20ejecutar_3a_7',['Pasos para ejecutar:',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md1',1,'']]],
  ['peticiones_20de_20ejemplo_20para_20postman_8',['📮 Peticiones de Ejemplo para Postman',['../md_POSTMAN-EXAMPLES.html',1,'']]],
  ['peticiones_20rápidas_20para_20postman_9',['📮 PETICIONES RÁPIDAS PARA POSTMAN',['../md_QUICK-START.html#autotoc_md51',1,'']]],
  ['peticiones_3a_10',['Cómo crear las peticiones:',['../md_POSTMAN-EXAMPLES.html#autotoc_md43',1,'']]],
  ['post_20api_20login_20éxito_11',['✅ POST /api/login (Éxito)',['../md_QUICK-START.html#autotoc_md65',1,'']]],
  ['post_20api_20login_20cashier_20existente_12',['POST /api/login (cashier existente)',['../md_TEST-INSTRUCTIONS.html#autotoc_md93',1,'']]],
  ['post_20api_20login_20cashier_20no_20existente_13',['POST /api/login (cashier no existente)',['../md_TEST-INSTRUCTIONS.html#autotoc_md94',1,'']]],
  ['post_20api_20login_20error_20usuario_20no_20existe_14',['❌ POST /api/login (Error - Usuario No Existe)',['../md_QUICK-START.html#autotoc_md66',1,'']]],
  ['post_20api_20login_20error_20validación_15',['❌ POST /api/login (Error - Validación)',['../md_QUICK-START.html#autotoc_md67',1,'']]],
  ['post_20error_20de_20validación_20nombre_20vacío_16',['6️⃣ POST - Error de Validación (Nombre Vacío)',['../md_QUICK-START.html#autotoc_md60',1,'']]],
  ['post_20login_20con_20otro_20cajero_17',['4️⃣ POST - Login con Otro Cajero',['../md_QUICK-START.html#autotoc_md58',1,'']]],
  ['post_20login_20de_20cajero_20éxito_18',['3️⃣ POST - Login de Cajero (Éxito)',['../md_POSTMAN-EXAMPLES.html#autotoc_md26',1,'']]],
  ['post_20login_20de_20cajero_20cajero_20no_20existente_19',['4️⃣ POST - Login de Cajero (Cajero No Existente)',['../md_POSTMAN-EXAMPLES.html#autotoc_md30',1,'']]],
  ['post_20login_20de_20cajero_20otro_20cajero_20válido_20',['5️⃣ POST - Login de Cajero (Otro cajero válido)',['../md_POSTMAN-EXAMPLES.html#autotoc_md34',1,'']]],
  ['post_20login_20exitoso_21',['3️⃣ POST - Login Exitoso',['../md_QUICK-START.html#autotoc_md57',1,'']]],
  ['post_20login_20fallido_20usuario_20no_20existe_22',['5️⃣ POST - Login Fallido (Usuario No Existe)',['../md_QUICK-START.html#autotoc_md59',1,'']]],
  ['post_20login_20sin_20nombre_20error_20de_20validación_23',['6️⃣ POST - Login sin nombre (Error de validación)',['../md_POSTMAN-EXAMPLES.html#autotoc_md38',1,'']]],
  ['postman_24',['📮 PETICIONES RÁPIDAS PARA POSTMAN',['../md_QUICK-START.html#autotoc_md51',1,'']]],
  ['postman_25',['Postman',['../md_POSTMAN-EXAMPLES.html#autotoc_md42',1,'📝 Notas para Postman'],['../md_POSTMAN-EXAMPLES.html',1,'📮 Peticiones de Ejemplo para Postman']]],
  ['powershell_26',['Opción C: Tests manuales con PowerShell',['../md_TEST-INSTRUCTIONS.html#autotoc_md89',1,'']]],
  ['powershell_20o_20cmd_20en_20el_20directorio_20del_20proyecto_27',['1. Abrir PowerShell o CMD en el directorio del proyecto',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md2',1,'']]],
  ['prerequisitos_28',['Prerequisitos',['../md_TEST-INSTRUCTIONS.html#autotoc_md81',1,'']]],
  ['project3_29',['❌ Error &quot;Unknown database &apos;project3&apos;&quot;',['../md_QUICK-START.html#autotoc_md73',1,'']]],
  ['project3_20fue_20creada_30',['5. Verificar que la base de datos &lt;span class=&quot;tt&quot;&gt;project3&lt;/span&gt; fue creada',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md6',1,'']]],
  ['proyecto_31',['1. Abrir PowerShell o CMD en el directorio del proyecto',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md2',1,'']]]
];
