var searchData=
[
  ['ejecutar_20el_20apiclient_20independiente_0',['Ejecutar el ApiClient independiente',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md14',1,'']]],
  ['ejecutar_20el_20servidor_20spring_20boot_1',['Compilar y ejecutar el servidor Spring Boot',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md12',1,'']]],
  ['ejecutar_3a_2',['Pasos para ejecutar:',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md1',1,'']]],
  ['ejemplo_3',['7. Consultar datos de ejemplo',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md8',1,'']]],
  ['ejemplo_20para_20postman_4',['📮 Peticiones de Ejemplo para Postman',['../md_POSTMAN-EXAMPLES.html',1,'']]],
  ['el_20apiclient_20independiente_5',['Ejecutar el ApiClient independiente',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md14',1,'']]],
  ['el_20contenedor_6',['Detener el contenedor',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md9',1,'']]],
  ['el_20contenedor_20está_20corriendo_7',['3. Verificar que el contenedor está corriendo',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md4',1,'']]],
  ['el_20contenedor_20mysql_20con_20docker_20compose_8',['2. Levantar el contenedor MySQL con Docker Compose',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md3',1,'']]],
  ['el_20contenedor_20y_20volúmenes_20datos_20completos_9',['Eliminar el contenedor y volúmenes (datos completos)',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md10',1,'']]],
  ['el_20directorio_20del_20proyecto_10',['1. Abrir PowerShell o CMD en el directorio del proyecto',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md2',1,'']]],
  ['el_20middleware_11',['🧪 Cómo Testear el Middleware',['../md_TEST-INSTRUCTIONS.html',1,'']]],
  ['el_20script_20automático_20recomendado_12',['Opción A: Usando el script automático (Recomendado)',['../md_TEST-INSTRUCTIONS.html#autotoc_md84',1,'']]],
  ['el_20servidor_13',['Paso 2: Compilar y arrancar el servidor',['../md_TEST-INSTRUCTIONS.html#autotoc_md83',1,'']]],
  ['el_20servidor_20spring_20boot_14',['Compilar y ejecutar el servidor Spring Boot',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md12',1,'']]],
  ['eliminar_20el_20contenedor_20y_20volúmenes_20datos_20completos_15',['Eliminar el contenedor y volúmenes (datos completos)',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md10',1,'']]],
  ['en_20el_20directorio_20del_20proyecto_16',['1. Abrir PowerShell o CMD en el directorio del proyecto',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md2',1,'']]],
  ['en_20la_20base_20de_20datos_17',['Cashiers válidos en la base de datos',['../md_TEST-INSTRUCTIONS.html#autotoc_md95',1,'']]],
  ['en_20la_20bd_18',['🎯 Cajeros Válidos en la BD',['../md_QUICK-START.html#autotoc_md69',1,'']]],
  ['en_20la_20bd_3a_19',['Cashiers válidos en la BD:',['../md_POSTMAN-EXAMPLES.html#autotoc_md44',1,'']]],
  ['endpoints_20',['Paso 3: Testear los endpoints',['../md_TEST-INSTRUCTIONS.html#autotoc_md86',1,'']]],
  ['endpoints_20disponibles_21',['Endpoints disponibles',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md13',1,'']]],
  ['entorno_20opcional_20_3a_22',['Variables de entorno (Opcional):',['../md_POSTMAN-EXAMPLES.html#autotoc_md45',1,'']]],
  ['error_20connection_20refused_23',['❌ Error &quot;Connection refused&quot;',['../md_QUICK-START.html#autotoc_md72',1,'']]],
  ['error_20de_20compilación_24',['❌ Error de compilación',['../md_QUICK-START.html#autotoc_md74',1,'']]],
  ['error_20de_20validación_25',['6️⃣ POST - Login sin nombre (Error de validación)',['../md_POSTMAN-EXAMPLES.html#autotoc_md38',1,'']]],
  ['error_20de_20validación_20nombre_20vacío_26',['6️⃣ POST - Error de Validación (Nombre Vacío)',['../md_QUICK-START.html#autotoc_md60',1,'']]],
  ['error_20unknown_20database_20project3_27',['❌ Error &quot;Unknown database &apos;project3&apos;&quot;',['../md_QUICK-START.html#autotoc_md73',1,'']]],
  ['error_20usuario_20no_20existe_28',['❌ POST /api/login (Error - Usuario No Existe)',['../md_QUICK-START.html#autotoc_md66',1,'']]],
  ['error_20validación_29',['❌ POST /api/login (Error - Validación)',['../md_QUICK-START.html#autotoc_md67',1,'']]],
  ['esperada_20200_20ok_30',['esperada 200 OK',['../md_POSTMAN-EXAMPLES.html#autotoc_md20',1,'Response esperada (200 OK)'],['../md_POSTMAN-EXAMPLES.html#autotoc_md24',1,'Response esperada (200 OK)'],['../md_POSTMAN-EXAMPLES.html#autotoc_md28',1,'Response esperada (200 OK)'],['../md_POSTMAN-EXAMPLES.html#autotoc_md32',1,'Response esperada (200 OK)'],['../md_POSTMAN-EXAMPLES.html#autotoc_md36',1,'Response esperada (200 OK)']]],
  ['esperada_20400_20bad_20request_31',['Response esperada (400 Bad Request)',['../md_POSTMAN-EXAMPLES.html#autotoc_md40',1,'']]],
  ['esperadas_32',['📊 Respuestas Esperadas',['../md_QUICK-START.html#autotoc_md62',1,'']]],
  ['esperadas_33',['Respuestas esperadas',['../md_TEST-INSTRUCTIONS.html#autotoc_md90',1,'']]],
  ['está_20corriendo_34',['3. Verificar que el contenedor está corriendo',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md4',1,'']]],
  ['estado_20del_20servidor_35',['✅ Estado del Servidor',['../md_QUICK-START.html#autotoc_md49',1,'']]],
  ['existe_36',['Existe',['../md_QUICK-START.html#autotoc_md66',1,'❌ POST /api/login (Error - Usuario No Existe)'],['../md_QUICK-START.html#autotoc_md59',1,'5️⃣ POST - Login Fallido (Usuario No Existe)']]],
  ['existente_37',['4️⃣ POST - Login de Cajero (Cajero No Existente)',['../md_POSTMAN-EXAMPLES.html#autotoc_md30',1,'']]],
  ['existente_38',['existente',['../md_TEST-INSTRUCTIONS.html#autotoc_md93',1,'POST /api/login (cashier existente)'],['../md_TEST-INSTRUCTIONS.html#autotoc_md94',1,'POST /api/login (cashier no existente)']]],
  ['exitoso_39',['3️⃣ POST - Login Exitoso',['../md_QUICK-START.html#autotoc_md57',1,'']]]
];
