var searchData=
[
  ['cómo_20crear_20las_20peticiones_3a_0',['Cómo crear las peticiones:',['../md_POSTMAN-EXAMPLES.html#autotoc_md43',1,'']]],
  ['cómo_20testear_20el_20middleware_1',['🧪 Cómo Testear el Middleware',['../md_TEST-INSTRUCTIONS.html',1,'']]],
  ['c_3a_20tests_20manuales_20con_20powershell_2',['Opción C: Tests manuales con PowerShell',['../md_TEST-INSTRUCTIONS.html#autotoc_md89',1,'']]],
  ['cajero_3',['4️⃣ POST - Login con Otro Cajero',['../md_QUICK-START.html#autotoc_md58',1,'']]],
  ['cajero_20éxito_4',['3️⃣ POST - Login de Cajero (Éxito)',['../md_POSTMAN-EXAMPLES.html#autotoc_md26',1,'']]],
  ['cajero_20cajero_20no_20existente_5',['4️⃣ POST - Login de Cajero (Cajero No Existente)',['../md_POSTMAN-EXAMPLES.html#autotoc_md30',1,'']]],
  ['cajero_20no_20existente_6',['4️⃣ POST - Login de Cajero (Cajero No Existente)',['../md_POSTMAN-EXAMPLES.html#autotoc_md30',1,'']]],
  ['cajero_20otro_20cajero_20válido_7',['5️⃣ POST - Login de Cajero (Otro cajero válido)',['../md_POSTMAN-EXAMPLES.html#autotoc_md34',1,'']]],
  ['cajero_20válido_8',['5️⃣ POST - Login de Cajero (Otro cajero válido)',['../md_POSTMAN-EXAMPLES.html#autotoc_md34',1,'']]],
  ['cajeros_20válidos_20en_20la_20bd_9',['🎯 Cajeros Válidos en la BD',['../md_QUICK-START.html#autotoc_md69',1,'']]],
  ['cashier_20existente_10',['POST /api/login (cashier existente)',['../md_TEST-INSTRUCTIONS.html#autotoc_md93',1,'']]],
  ['cashier_20no_20existente_11',['POST /api/login (cashier no existente)',['../md_TEST-INSTRUCTIONS.html#autotoc_md94',1,'']]],
  ['cashiers_20válidos_20en_20la_20base_20de_20datos_12',['Cashiers válidos en la base de datos',['../md_TEST-INSTRUCTIONS.html#autotoc_md95',1,'']]],
  ['cashiers_20válidos_20en_20la_20bd_3a_13',['Cashiers válidos en la BD:',['../md_POSTMAN-EXAMPLES.html#autotoc_md44',1,'']]],
  ['cmd_20en_20el_20directorio_20del_20proyecto_14',['1. Abrir PowerShell o CMD en el directorio del proyecto',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md2',1,'']]],
  ['colección_20más_20fácil_15',['🔹 Opción 1: Importar Colección (MÁS FÁCIL)',['../md_QUICK-START.html#autotoc_md52',1,'']]],
  ['compilación_16',['❌ Error de compilación',['../md_QUICK-START.html#autotoc_md74',1,'']]],
  ['compilar_20y_20arrancar_20el_20servidor_17',['Paso 2: Compilar y arrancar el servidor',['../md_TEST-INSTRUCTIONS.html#autotoc_md83',1,'']]],
  ['compilar_20y_20ejecutar_20el_20servidor_20spring_20boot_18',['Compilar y ejecutar el servidor Spring Boot',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md12',1,'']]],
  ['completo_19',['Completo',['../md_QUICK-START.html#autotoc_md56',1,'2️⃣ GET - Menú Completo'],['../md_POSTMAN-EXAMPLES.html#autotoc_md22',1,'2️⃣ GET - Obtener Menú Completo']]],
  ['completos_20',['Eliminar el contenedor y volúmenes (datos completos)',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md10',1,'']]],
  ['compose_21',['2. Levantar el contenedor MySQL con Docker Compose',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md3',1,'']]],
  ['con_20curl_22',['Opción B: Tests manuales con curl',['../md_TEST-INSTRUCTIONS.html#autotoc_md88',1,'']]],
  ['con_20docker_23',['Instrucciones para levantar la base de datos MySQL con Docker',['../md_DOCKER-INSTRUCTIONS.html',1,'']]],
  ['con_20docker_20compose_24',['2. Levantar el contenedor MySQL con Docker Compose',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md3',1,'']]],
  ['con_20otro_20cajero_25',['4️⃣ POST - Login con Otro Cajero',['../md_QUICK-START.html#autotoc_md58',1,'']]],
  ['con_20powershell_26',['Opción C: Tests manuales con PowerShell',['../md_TEST-INSTRUCTIONS.html#autotoc_md89',1,'']]],
  ['configuración_20de_20la_20bbdd_20mysql_20mariadb_27',['Configuración de la BBDD (MySQL / MariaDB)',['../md_README.html#autotoc_md79',1,'']]],
  ['connection_20refused_28',['❌ Error &quot;Connection refused&quot;',['../md_QUICK-START.html#autotoc_md72',1,'']]],
  ['consultar_20datos_20de_20ejemplo_29',['7. Consultar datos de ejemplo',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md8',1,'']]],
  ['contenedor_30',['Detener el contenedor',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md9',1,'']]],
  ['contenedor_20está_20corriendo_31',['3. Verificar que el contenedor está corriendo',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md4',1,'']]],
  ['contenedor_20mysql_20con_20docker_20compose_32',['2. Levantar el contenedor MySQL con Docker Compose',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md3',1,'']]],
  ['contenedor_20y_20volúmenes_20datos_20completos_33',['Eliminar el contenedor y volúmenes (datos completos)',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md10',1,'']]],
  ['corriendo_34',['3. Verificar que el contenedor está corriendo',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md4',1,'']]],
  ['creada_35',['5. Verificar que la base de datos &lt;span class=&quot;tt&quot;&gt;project3&lt;/span&gt; fue creada',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md6',1,'']]],
  ['creadas_36',['6. Verificar las tablas creadas',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md7',1,'']]],
  ['crear_20las_20peticiones_3a_37',['Cómo crear las peticiones:',['../md_POSTMAN-EXAMPLES.html#autotoc_md43',1,'']]],
  ['crear_20manualmente_38',['🔹 Opción 2: Crear Manualmente',['../md_QUICK-START.html#autotoc_md54',1,'']]],
  ['credenciales_20de_20la_20base_20de_20datos_39',['Credenciales de la base de datos',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md11',1,'']]],
  ['curl_40',['Opción B: Tests manuales con curl',['../md_TEST-INSTRUCTIONS.html#autotoc_md88',1,'']]]
];
