var searchData=
[
  ['database_20project3_0',['❌ Error &quot;Unknown database &apos;project3&apos;&quot;',['../md_QUICK-START.html#autotoc_md73',1,'']]],
  ['datos_1',['🔍 Verificación de la Base de Datos',['../md_POSTMAN-EXAMPLES.html#autotoc_md47',1,'']]],
  ['datos_2',['datos',['../md_TEST-INSTRUCTIONS.html#autotoc_md95',1,'Cashiers válidos en la base de datos'],['../md_DOCKER-INSTRUCTIONS.html#autotoc_md11',1,'Credenciales de la base de datos']]],
  ['datos_20completos_3',['Eliminar el contenedor y volúmenes (datos completos)',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md10',1,'']]],
  ['datos_20de_20ejemplo_4',['7. Consultar datos de ejemplo',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md8',1,'']]],
  ['datos_20mysql_5',['Paso 1: Levantar la base de datos MySQL',['../md_TEST-INSTRUCTIONS.html#autotoc_md82',1,'']]],
  ['datos_20mysql_20con_20docker_6',['Instrucciones para levantar la base de datos MySQL con Docker',['../md_DOCKER-INSTRUCTIONS.html',1,'']]],
  ['datos_20project3_20fue_20creada_7',['5. Verificar que la base de datos &lt;span class=&quot;tt&quot;&gt;project3&lt;/span&gt; fue creada',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md6',1,'']]],
  ['de_20cajero_20éxito_8',['3️⃣ POST - Login de Cajero (Éxito)',['../md_POSTMAN-EXAMPLES.html#autotoc_md26',1,'']]],
  ['de_20cajero_20cajero_20no_20existente_9',['4️⃣ POST - Login de Cajero (Cajero No Existente)',['../md_POSTMAN-EXAMPLES.html#autotoc_md30',1,'']]],
  ['de_20cajero_20otro_20cajero_20válido_10',['5️⃣ POST - Login de Cajero (Otro cajero válido)',['../md_POSTMAN-EXAMPLES.html#autotoc_md34',1,'']]],
  ['de_20compilación_11',['❌ Error de compilación',['../md_QUICK-START.html#autotoc_md74',1,'']]],
  ['de_20datos_12',['🔍 Verificación de la Base de Datos',['../md_POSTMAN-EXAMPLES.html#autotoc_md47',1,'']]],
  ['de_20datos_13',['de datos',['../md_TEST-INSTRUCTIONS.html#autotoc_md95',1,'Cashiers válidos en la base de datos'],['../md_DOCKER-INSTRUCTIONS.html#autotoc_md11',1,'Credenciales de la base de datos']]],
  ['de_20datos_20mysql_14',['Paso 1: Levantar la base de datos MySQL',['../md_TEST-INSTRUCTIONS.html#autotoc_md82',1,'']]],
  ['de_20datos_20mysql_20con_20docker_15',['Instrucciones para levantar la base de datos MySQL con Docker',['../md_DOCKER-INSTRUCTIONS.html',1,'']]],
  ['de_20datos_20project3_20fue_20creada_16',['5. Verificar que la base de datos &lt;span class=&quot;tt&quot;&gt;project3&lt;/span&gt; fue creada',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md6',1,'']]],
  ['de_20ejemplo_17',['7. Consultar datos de ejemplo',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md8',1,'']]],
  ['de_20ejemplo_20para_20postman_18',['📮 Peticiones de Ejemplo para Postman',['../md_POSTMAN-EXAMPLES.html',1,'']]],
  ['de_20entorno_20opcional_20_3a_19',['Variables de entorno (Opcional):',['../md_POSTMAN-EXAMPLES.html#autotoc_md45',1,'']]],
  ['de_20inicialización_20opcional_20',['4. Ver los logs de inicialización (opcional)',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md5',1,'']]],
  ['de_20la_20base_20de_20datos_21',['🔍 Verificación de la Base de Datos',['../md_POSTMAN-EXAMPLES.html#autotoc_md47',1,'']]],
  ['de_20la_20base_20de_20datos_22',['Credenciales de la base de datos',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md11',1,'']]],
  ['de_20la_20bbdd_20mysql_20mariadb_23',['Configuración de la BBDD (MySQL / MariaDB)',['../md_README.html#autotoc_md79',1,'']]],
  ['de_20referencia_24',['📁 Archivos de Referencia',['../md_QUICK-START.html#autotoc_md76',1,'']]],
  ['de_20testing_25',['🚀 SERVIDOR LANZADO - Guía Rápida de Testing',['../md_QUICK-START.html',1,'']]],
  ['de_20tests_20recomendado_26',['Opción A: Script automático de tests (Recomendado)',['../md_TEST-INSTRUCTIONS.html#autotoc_md87',1,'']]],
  ['de_20validación_27',['6️⃣ POST - Login sin nombre (Error de validación)',['../md_POSTMAN-EXAMPLES.html#autotoc_md38',1,'']]],
  ['de_20validación_20nombre_20vacío_28',['6️⃣ POST - Error de Validación (Nombre Vacío)',['../md_QUICK-START.html#autotoc_md60',1,'']]],
  ['del_20proyecto_29',['1. Abrir PowerShell o CMD en el directorio del proyecto',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md2',1,'']]],
  ['del_20restaurante_30',['del Restaurante',['../md_QUICK-START.html#autotoc_md55',1,'1️⃣ GET - Info del Restaurante'],['../md_POSTMAN-EXAMPLES.html#autotoc_md18',1,'1️⃣ GET - Información del Restaurante']]],
  ['del_20servidor_31',['✅ Estado del Servidor',['../md_QUICK-START.html#autotoc_md49',1,'']]],
  ['detener_20el_20contenedor_32',['Detener el contenedor',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md9',1,'']]],
  ['detener_20todo_33',['Detener todo',['../md_TEST-INSTRUCTIONS.html#autotoc_md96',1,'']]],
  ['directorio_20del_20proyecto_34',['1. Abrir PowerShell o CMD en el directorio del proyecto',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md2',1,'']]],
  ['disponibles_35',['Endpoints disponibles',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md13',1,'']]],
  ['docker_36',['Instrucciones para levantar la base de datos MySQL con Docker',['../md_DOCKER-INSTRUCTIONS.html',1,'']]],
  ['docker_20compose_37',['2. Levantar el contenedor MySQL con Docker Compose',['../md_DOCKER-INSTRUCTIONS.html#autotoc_md3',1,'']]]
];
